SET DEFINE OFF;

GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.INDUCTION_AUDIT TO HHS_WHRSC_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_WHRSC_HR.OPDIV_AFFILIATION TO HHS_WHRSC_HR_RW_ROLE;
