SET DEFINE OFF;


CREATE TABLE HHS_WHRSC_HR.OPDIV_AFFILIATION
(
      OPDIV VARCHAR2(8),
      AFFILIATION VARCHAR2(4),
      AFFILIATION_CODE VARCHAR2(16)
);

DELETE FROM HHS_WHRSC_HR.OPDIV_AFFILIATION;

COMMIT;

ALTER TABLE HHS_WHRSC_HR.OPDIV_AFFILIATION MODIFY AFFILIATION_CODE VARCHAR2(32);
ALTER TABLE HHS_WHRSC_HR.OPDIV_AFFILIATION MODIFY AFFILIATION VARCHAR2(32);

/


