SET DEFINE OFF;

ALTER TABLE SPA_PROCESSING ADD EFFECTIVE_DATE DATE;

ALTER TABLE HHS_WHRSC_HR.RECRUITMENT ADD RECRUITMENT_PCKG_QUALITY VARCHAR2(20);
ALTER TABLE HHS_WHRSC_HR.RECRUITMENT ADD APPLICANT_LIMIT NUMBER(5,0);
ALTER TABLE HHS_WHRSC_HR.ANNOUNCEMENT ADD ANN_QUALITY VARCHAR2(20);
ALTER TABLE HHS_WHRSC_HR.APPLICANT_RATING ADD APPLICANT_RATING_QUALITY VARCHAR2(20);

/
