SET DEFINE OFF;

UPDATE HHS_WHRSC_HR.TYPE_VALUES SET DISP_ORDER = 10 WHERE TYPE_NAME = 'rybCodeList' AND TYPE_VALUE = 'Green';
UPDATE HHS_WHRSC_HR.TYPE_VALUES SET DISP_ORDER = 20 WHERE TYPE_NAME = 'rybCodeList' AND TYPE_VALUE = 'Yellow';
UPDATE HHS_WHRSC_HR.TYPE_VALUES SET DISP_ORDER = 30 WHERE TYPE_NAME = 'rybCodeList' AND TYPE_VALUE = 'Red';

Insert into HHS_WHRSC_HR.TYPE_values (TYPE_NAME,TYPE_VALUE,CONDITION_1,CONDITION_2,DISP_ORDER,TYPE_CODE) values('Other Recruitment Considerations','Direct Hire',null,';ALL;',10,null);

commit;