--------------------------------
-- DDL FOR APPOINTMENT VIEWS           
--------------------------------
--------------------------------

---------------------
--VW_A_VAC_ANN_RESULT
---------------------
CREATE OR REPLACE VIEW HHS_WHRSC_HR.VW_A_VAC_ANN_RESULT
AS
SELECT
	NH_REQUEST_NUMBER || TO_CHAR(DNHVR.NH_VACANCY_NUMBER) AS REQ_VAC,
	NH_REQUEST_NUMBER AS REQUEST_NUMBER,
	TO_CHAR(DNHVR.NH_VACANCY_NUMBER) AS VACANCY_NUMBER,
	VACANCY_ANNOUNCEMENT_NUMBER ,
	SUPERVISORY_POSITION,
	CASE WHEN DNHF.ROWID IS NOT NULL
		THEN 'Yes'
		ELSE 'No'
	END AS OF_306_ASSGND_IN_ONBRDG_MNGR,
	REQUEST_TYPE AS RLTSHP_TO_RCRMT_ACTN,
	NH_POSITION_DESCRIPTION_NUMBER AS JOB_CODE,
	CLEARANCE_LEVEL_REQUIRED,
	CASE WHEN
		DNHVR.NH_VACANCY_NUMBER IS NOT NULL 
		THEN 'Competitive'
		ELSE 'Non-Competitive'
	END AS TYPE_OF_SELECTION,
	NVL(NH_ACTUAL_START_DATE, NH_PROJECTED_START_DATE) AS EOD
FROM HHS_WHRSC_HR.DSS_NEW_HIRE_VACANCY_REQUEST DNHVR
	LEFT JOIN HHS_WHRSC_HR.DSS_VACANCY DV
		ON DNHVR.NH_VACANCY_NUMBER = DV.VACANCY_IDENTIFICATION_NUMBER
	LEFT JOIN HHS_WHRSC_HR.DSS_REQUESTS DR
		ON DNHVR.NH_REQUEST_NUMBER = DR.REQUEST_NUMBER
	LEFT JOIN HHS_WHRSC_HR.DSS_NEW_HIRE_FORMS DNHF
		ON DNHVR.NEW_HIRE_NUMBER = DNHF.NEW_HIRE_NUMBER
		AND DNHF.NH_FORM_NUMBER = 'OF 306'
	LEFT JOIN HHS_WHRSC_HR.DSS_NEW_HIRES DNH
		ON DNHVR.NEW_HIRE_NUMBER = DNH.NEW_HIRE_NUMBER
WHERE NH_REQUEST_NUMBER IS NOT NULL;