//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 				This type defines information gathered from a 
 * 				card certificate.
 * 			
 * 
 * <p>Java class for CardCertificateInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CardCertificateInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CertCheckResult" type="{http://hspd12.hhs.gov/piv/binding/v1}CertificateCheckResultType"/&gt;
 *         &lt;element name="CertCheckResultStr" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CertFriendlyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CertNotBefore" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="CertNotAfter" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="CertIssuerDN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CertSubjectDN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CertSerialNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AdditionalCertData" type="{http://hspd12.hhs.gov/piv/binding/v1}TaggedDataType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CardCertificateInfoType", namespace = "http://hspd12.hhs.gov/piv/binding/v1", propOrder = {
    "certCheckResult",
    "certCheckResultStr",
    "certFriendlyName",
    "certNotBefore",
    "certNotAfter",
    "certIssuerDN",
    "certSubjectDN",
    "certSerialNumber",
    "additionalCertData"
})
public class CardCertificateInfoType {

    @XmlElement(name = "CertCheckResult", required = true)
    @XmlSchemaType(name = "string")
    protected CertificateCheckResultType certCheckResult;
    @XmlElement(name = "CertCheckResultStr", required = true)
    protected String certCheckResultStr;
    @XmlElement(name = "CertFriendlyName")
    protected String certFriendlyName;
    @XmlElement(name = "CertNotBefore")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar certNotBefore;
    @XmlElement(name = "CertNotAfter")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar certNotAfter;
    @XmlElement(name = "CertIssuerDN")
    protected String certIssuerDN;
    @XmlElement(name = "CertSubjectDN")
    protected String certSubjectDN;
    @XmlElement(name = "CertSerialNumber")
    protected String certSerialNumber;
    @XmlElement(name = "AdditionalCertData")
    protected List<TaggedDataType> additionalCertData;

    /**
     * Gets the value of the certCheckResult property.
     * 
     * @return
     *     possible object is
     *     {@link CertificateCheckResultType }
     *     
     */
    public CertificateCheckResultType getCertCheckResult() {
        return certCheckResult;
    }

    /**
     * Sets the value of the certCheckResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertificateCheckResultType }
     *     
     */
    public void setCertCheckResult(CertificateCheckResultType value) {
        this.certCheckResult = value;
    }

    /**
     * Gets the value of the certCheckResultStr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertCheckResultStr() {
        return certCheckResultStr;
    }

    /**
     * Sets the value of the certCheckResultStr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertCheckResultStr(String value) {
        this.certCheckResultStr = value;
    }

    /**
     * Gets the value of the certFriendlyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertFriendlyName() {
        return certFriendlyName;
    }

    /**
     * Sets the value of the certFriendlyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertFriendlyName(String value) {
        this.certFriendlyName = value;
    }

    /**
     * Gets the value of the certNotBefore property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCertNotBefore() {
        return certNotBefore;
    }

    /**
     * Sets the value of the certNotBefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCertNotBefore(XMLGregorianCalendar value) {
        this.certNotBefore = value;
    }

    /**
     * Gets the value of the certNotAfter property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCertNotAfter() {
        return certNotAfter;
    }

    /**
     * Sets the value of the certNotAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCertNotAfter(XMLGregorianCalendar value) {
        this.certNotAfter = value;
    }

    /**
     * Gets the value of the certIssuerDN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertIssuerDN() {
        return certIssuerDN;
    }

    /**
     * Sets the value of the certIssuerDN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertIssuerDN(String value) {
        this.certIssuerDN = value;
    }

    /**
     * Gets the value of the certSubjectDN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertSubjectDN() {
        return certSubjectDN;
    }

    /**
     * Sets the value of the certSubjectDN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertSubjectDN(String value) {
        this.certSubjectDN = value;
    }

    /**
     * Gets the value of the certSerialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertSerialNumber() {
        return certSerialNumber;
    }

    /**
     * Sets the value of the certSerialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertSerialNumber(String value) {
        this.certSerialNumber = value;
    }

    /**
     * Gets the value of the additionalCertData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalCertData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalCertData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaggedDataType }
     * 
     * 
     */
    public List<TaggedDataType> getAdditionalCertData() {
        if (additionalCertData == null) {
            additionalCertData = new ArrayList<TaggedDataType>();
        }
        return this.additionalCertData;
    }

}
