//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				This type defines the parameters for the Card State
 * 				Changed Notification event.
 * 			
 * 
 * <p>Java class for CardStateChangeNotifyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CardStateChangeNotifyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CardHolderPI" type="{http://hspd12.hhs.gov/federated/enrollment/v1}PersonIdType"/&gt;
 *         &lt;element name="NewCardState" type="{http://hspd12.hhs.gov/federated/enrollment/v1}CardStateEnumType"/&gt;
 *         &lt;element name="ReasonForChange"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="256"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CardStateChangeNotifyType", propOrder = {
    "cardHolderPI",
    "newCardState",
    "reasonForChange"
})
public class CardStateChangeNotifyType {

    @XmlElement(name = "CardHolderPI", required = true)
    protected String cardHolderPI;
    @XmlElement(name = "NewCardState", required = true)
    @XmlSchemaType(name = "string")
    protected CardStateEnumType newCardState;
    @XmlElement(name = "ReasonForChange", required = true)
    protected String reasonForChange;

    /**
     * Gets the value of the cardHolderPI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardHolderPI() {
        return cardHolderPI;
    }

    /**
     * Sets the value of the cardHolderPI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardHolderPI(String value) {
        this.cardHolderPI = value;
    }

    /**
     * Gets the value of the newCardState property.
     * 
     * @return
     *     possible object is
     *     {@link CardStateEnumType }
     *     
     */
    public CardStateEnumType getNewCardState() {
        return newCardState;
    }

    /**
     * Sets the value of the newCardState property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardStateEnumType }
     *     
     */
    public void setNewCardState(CardStateEnumType value) {
        this.newCardState = value;
    }

    /**
     * Gets the value of the reasonForChange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonForChange() {
        return reasonForChange;
    }

    /**
     * Sets the value of the reasonForChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonForChange(String value) {
        this.reasonForChange = value;
    }

}
