//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 				This type defines information extracted from the 
 * 				PIV compliant card being bound.
 * 			
 * 
 * <p>Java class for CardExtractedInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CardExtractedInformationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CardType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FascnAgencyCode" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/&gt;
 *         &lt;element name="FascnAgencyCodeStr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FascnSystemCode" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/&gt;
 *         &lt;element name="FascnSystemCodeStr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FascnCredentialNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/&gt;
 *         &lt;element name="FascnCredentialNumberStr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FascnIndividualCredentialIssue" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/&gt;
 *         &lt;element name="FascnCredentialSeries" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/&gt;
 *         &lt;element name="FascnPersonIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FascnOrganizationalCategory" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/&gt;
 *         &lt;element name="FascnOrganizationalCategoryStr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FascnOrganizationalIdentifier" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/&gt;
 *         &lt;element name="FascnOrganizationalIdentifierStr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FascnPersonOrganizationAssociation" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/&gt;
 *         &lt;element name="FascnPersonOrganizationAssociationStr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CardExpirationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="CardExpirationDateStr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CardGUID" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;length value="32"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ChuidOrgIdentifier" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;length value="4"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ChuidDUNS" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;length value="9"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CardExtractedInformationType", namespace = "http://hspd12.hhs.gov/piv/binding/v1", propOrder = {
    "cardType",
    "fascnAgencyCode",
    "fascnAgencyCodeStr",
    "fascnSystemCode",
    "fascnSystemCodeStr",
    "fascnCredentialNumber",
    "fascnCredentialNumberStr",
    "fascnIndividualCredentialIssue",
    "fascnCredentialSeries",
    "fascnPersonIdentifier",
    "fascnOrganizationalCategory",
    "fascnOrganizationalCategoryStr",
    "fascnOrganizationalIdentifier",
    "fascnOrganizationalIdentifierStr",
    "fascnPersonOrganizationAssociation",
    "fascnPersonOrganizationAssociationStr",
    "cardExpirationDate",
    "cardExpirationDateStr",
    "cardGUID",
    "chuidOrgIdentifier",
    "chuidDUNS"
})
public class CardExtractedInformationType {

    @XmlElement(name = "CardType")
    protected String cardType;
    @XmlElement(name = "FascnAgencyCode")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer fascnAgencyCode;
    @XmlElement(name = "FascnAgencyCodeStr")
    protected String fascnAgencyCodeStr;
    @XmlElement(name = "FascnSystemCode")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer fascnSystemCode;
    @XmlElement(name = "FascnSystemCodeStr")
    protected String fascnSystemCodeStr;
    @XmlElement(name = "FascnCredentialNumber")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger fascnCredentialNumber;
    @XmlElement(name = "FascnCredentialNumberStr")
    protected String fascnCredentialNumberStr;
    @XmlElement(name = "FascnIndividualCredentialIssue")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer fascnIndividualCredentialIssue;
    @XmlElement(name = "FascnCredentialSeries")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer fascnCredentialSeries;
    @XmlElement(name = "FascnPersonIdentifier")
    protected String fascnPersonIdentifier;
    @XmlElement(name = "FascnOrganizationalCategory")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer fascnOrganizationalCategory;
    @XmlElement(name = "FascnOrganizationalCategoryStr")
    protected String fascnOrganizationalCategoryStr;
    @XmlElement(name = "FascnOrganizationalIdentifier")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer fascnOrganizationalIdentifier;
    @XmlElement(name = "FascnOrganizationalIdentifierStr")
    protected String fascnOrganizationalIdentifierStr;
    @XmlElement(name = "FascnPersonOrganizationAssociation")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer fascnPersonOrganizationAssociation;
    @XmlElement(name = "FascnPersonOrganizationAssociationStr")
    protected String fascnPersonOrganizationAssociationStr;
    @XmlElement(name = "CardExpirationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar cardExpirationDate;
    @XmlElement(name = "CardExpirationDateStr")
    protected String cardExpirationDateStr;
    @XmlElement(name = "CardGUID")
    protected String cardGUID;
    @XmlElement(name = "ChuidOrgIdentifier")
    protected String chuidOrgIdentifier;
    @XmlElement(name = "ChuidDUNS")
    protected String chuidDUNS;

    /**
     * Gets the value of the cardType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * Sets the value of the cardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardType(String value) {
        this.cardType = value;
    }

    /**
     * Gets the value of the fascnAgencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFascnAgencyCode() {
        return fascnAgencyCode;
    }

    /**
     * Sets the value of the fascnAgencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFascnAgencyCode(Integer value) {
        this.fascnAgencyCode = value;
    }

    /**
     * Gets the value of the fascnAgencyCodeStr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFascnAgencyCodeStr() {
        return fascnAgencyCodeStr;
    }

    /**
     * Sets the value of the fascnAgencyCodeStr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFascnAgencyCodeStr(String value) {
        this.fascnAgencyCodeStr = value;
    }

    /**
     * Gets the value of the fascnSystemCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFascnSystemCode() {
        return fascnSystemCode;
    }

    /**
     * Sets the value of the fascnSystemCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFascnSystemCode(Integer value) {
        this.fascnSystemCode = value;
    }

    /**
     * Gets the value of the fascnSystemCodeStr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFascnSystemCodeStr() {
        return fascnSystemCodeStr;
    }

    /**
     * Sets the value of the fascnSystemCodeStr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFascnSystemCodeStr(String value) {
        this.fascnSystemCodeStr = value;
    }

    /**
     * Gets the value of the fascnCredentialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFascnCredentialNumber() {
        return fascnCredentialNumber;
    }

    /**
     * Sets the value of the fascnCredentialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFascnCredentialNumber(BigInteger value) {
        this.fascnCredentialNumber = value;
    }

    /**
     * Gets the value of the fascnCredentialNumberStr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFascnCredentialNumberStr() {
        return fascnCredentialNumberStr;
    }

    /**
     * Sets the value of the fascnCredentialNumberStr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFascnCredentialNumberStr(String value) {
        this.fascnCredentialNumberStr = value;
    }

    /**
     * Gets the value of the fascnIndividualCredentialIssue property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFascnIndividualCredentialIssue() {
        return fascnIndividualCredentialIssue;
    }

    /**
     * Sets the value of the fascnIndividualCredentialIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFascnIndividualCredentialIssue(Integer value) {
        this.fascnIndividualCredentialIssue = value;
    }

    /**
     * Gets the value of the fascnCredentialSeries property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFascnCredentialSeries() {
        return fascnCredentialSeries;
    }

    /**
     * Sets the value of the fascnCredentialSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFascnCredentialSeries(Integer value) {
        this.fascnCredentialSeries = value;
    }

    /**
     * Gets the value of the fascnPersonIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFascnPersonIdentifier() {
        return fascnPersonIdentifier;
    }

    /**
     * Sets the value of the fascnPersonIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFascnPersonIdentifier(String value) {
        this.fascnPersonIdentifier = value;
    }

    /**
     * Gets the value of the fascnOrganizationalCategory property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFascnOrganizationalCategory() {
        return fascnOrganizationalCategory;
    }

    /**
     * Sets the value of the fascnOrganizationalCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFascnOrganizationalCategory(Integer value) {
        this.fascnOrganizationalCategory = value;
    }

    /**
     * Gets the value of the fascnOrganizationalCategoryStr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFascnOrganizationalCategoryStr() {
        return fascnOrganizationalCategoryStr;
    }

    /**
     * Sets the value of the fascnOrganizationalCategoryStr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFascnOrganizationalCategoryStr(String value) {
        this.fascnOrganizationalCategoryStr = value;
    }

    /**
     * Gets the value of the fascnOrganizationalIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFascnOrganizationalIdentifier() {
        return fascnOrganizationalIdentifier;
    }

    /**
     * Sets the value of the fascnOrganizationalIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFascnOrganizationalIdentifier(Integer value) {
        this.fascnOrganizationalIdentifier = value;
    }

    /**
     * Gets the value of the fascnOrganizationalIdentifierStr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFascnOrganizationalIdentifierStr() {
        return fascnOrganizationalIdentifierStr;
    }

    /**
     * Sets the value of the fascnOrganizationalIdentifierStr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFascnOrganizationalIdentifierStr(String value) {
        this.fascnOrganizationalIdentifierStr = value;
    }

    /**
     * Gets the value of the fascnPersonOrganizationAssociation property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFascnPersonOrganizationAssociation() {
        return fascnPersonOrganizationAssociation;
    }

    /**
     * Sets the value of the fascnPersonOrganizationAssociation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFascnPersonOrganizationAssociation(Integer value) {
        this.fascnPersonOrganizationAssociation = value;
    }

    /**
     * Gets the value of the fascnPersonOrganizationAssociationStr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFascnPersonOrganizationAssociationStr() {
        return fascnPersonOrganizationAssociationStr;
    }

    /**
     * Sets the value of the fascnPersonOrganizationAssociationStr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFascnPersonOrganizationAssociationStr(String value) {
        this.fascnPersonOrganizationAssociationStr = value;
    }

    /**
     * Gets the value of the cardExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCardExpirationDate() {
        return cardExpirationDate;
    }

    /**
     * Sets the value of the cardExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCardExpirationDate(XMLGregorianCalendar value) {
        this.cardExpirationDate = value;
    }

    /**
     * Gets the value of the cardExpirationDateStr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardExpirationDateStr() {
        return cardExpirationDateStr;
    }

    /**
     * Sets the value of the cardExpirationDateStr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardExpirationDateStr(String value) {
        this.cardExpirationDateStr = value;
    }

    /**
     * Gets the value of the cardGUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardGUID() {
        return cardGUID;
    }

    /**
     * Sets the value of the cardGUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardGUID(String value) {
        this.cardGUID = value;
    }

    /**
     * Gets the value of the chuidOrgIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChuidOrgIdentifier() {
        return chuidOrgIdentifier;
    }

    /**
     * Sets the value of the chuidOrgIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChuidOrgIdentifier(String value) {
        this.chuidOrgIdentifier = value;
    }

    /**
     * Gets the value of the chuidDUNS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChuidDUNS() {
        return chuidDUNS;
    }

    /**
     * Sets the value of the chuidDUNS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChuidDUNS(String value) {
        this.chuidDUNS = value;
    }

}
