//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 *         		Type definition for Card History data elements
 *         	
 * 
 * <p>Java class for CardHistoryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CardHistoryType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CHUID" type="{http://hspd12.hhs.gov/federated/enrollment/v1}CHUIDDataFieldsType" minOccurs="0"/&gt;
 *         &lt;element name="IssuedDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="RevokedDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="Status" type="{http://hspd12.hhs.gov/federated/enrollment/v1}CardStatusType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CardHistoryType", propOrder = {
    "chuid",
    "issuedDate",
    "revokedDate",
    "status"
})
public class CardHistoryType {

    @XmlElement(name = "CHUID")
    protected CHUIDDataFieldsType chuid;
    @XmlElement(name = "IssuedDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar issuedDate;
    @XmlElement(name = "RevokedDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar revokedDate;
    @XmlElement(name = "Status", required = true)
    @XmlSchemaType(name = "string")
    protected CardStatusType status;

    /**
     * Gets the value of the chuid property.
     * 
     * @return
     *     possible object is
     *     {@link CHUIDDataFieldsType }
     *     
     */
    public CHUIDDataFieldsType getCHUID() {
        return chuid;
    }

    /**
     * Sets the value of the chuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link CHUIDDataFieldsType }
     *     
     */
    public void setCHUID(CHUIDDataFieldsType value) {
        this.chuid = value;
    }

    /**
     * Gets the value of the issuedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIssuedDate() {
        return issuedDate;
    }

    /**
     * Sets the value of the issuedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIssuedDate(XMLGregorianCalendar value) {
        this.issuedDate = value;
    }

    /**
     * Gets the value of the revokedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRevokedDate() {
        return revokedDate;
    }

    /**
     * Sets the value of the revokedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRevokedDate(XMLGregorianCalendar value) {
        this.revokedDate = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link CardStatusType }
     *     
     */
    public CardStatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardStatusType }
     *     
     */
    public void setStatus(CardStatusType value) {
        this.status = value;
    }

}
