//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CertificateCheckResultType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CertificateCheckResultType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CertValid"/&gt;
 *     &lt;enumeration value="CertRevoked"/&gt;
 *     &lt;enumeration value="CertSuspended"/&gt;
 *     &lt;enumeration value="CertNotValid"/&gt;
 *     &lt;enumeration value="CertNotCurrentlyCheckable"/&gt;
 *     &lt;enumeration value="CertCheckAborted"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CertificateCheckResultType", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
@XmlEnum
public enum CertificateCheckResultType {


    /**
     * 
     * 					The certificate was checked and found to be valid.
     * 				
     * 
     */
    @XmlEnumValue("CertValid")
    CERT_VALID("CertValid"),

    /**
     * 
     * 					The certificate was checked and found to be revoked.
     * 				
     * 
     */
    @XmlEnumValue("CertRevoked")
    CERT_REVOKED("CertRevoked"),

    /**
     * 
     * 					The certificate was checked and found to be suspended.
     * 				
     * 
     */
    @XmlEnumValue("CertSuspended")
    CERT_SUSPENDED("CertSuspended"),

    /**
     * 
     * 					The certificate was checked and found to be invalid
     * 					for some other reason than being suspended or revoked.
     * 				
     * 
     */
    @XmlEnumValue("CertNotValid")
    CERT_NOT_VALID("CertNotValid"),

    /**
     * 
     * 					The certificate status could not be checked at the
     * 					time the request was submitted.  This usually
     * 					indicates that the OCSP responder specified in the
     * 					certificate could not be successfully queried.
     * 				
     * 
     */
    @XmlEnumValue("CertNotCurrentlyCheckable")
    CERT_NOT_CURRENTLY_CHECKABLE("CertNotCurrentlyCheckable"),

    /**
     * 
     * 					The certificate was not checked because a previous event
     * 					caused further certificate checking to be aborted..
     * 				
     * 
     */
    @XmlEnumValue("CertCheckAborted")
    CERT_CHECK_ABORTED("CertCheckAborted");
    private final String value;

    CertificateCheckResultType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CertificateCheckResultType fromValue(String v) {
        for (CertificateCheckResultType c: CertificateCheckResultType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
