//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PivAuthenticationCertResult" type="{http://hspd12.hhs.gov/piv/binding/v1}CertificateCheckResultType" minOccurs="0"/&gt;
 *         &lt;element name="PivDigitalSignatureCertResult" type="{http://hspd12.hhs.gov/piv/binding/v1}CertificateCheckResultType" minOccurs="0"/&gt;
 *         &lt;element name="PivKeyManagementCertResult" type="{http://hspd12.hhs.gov/piv/binding/v1}CertificateCheckResultType" minOccurs="0"/&gt;
 *         &lt;element name="PivCardAuthenticationCertResult" type="{http://hspd12.hhs.gov/piv/binding/v1}CertificateCheckResultType" minOccurs="0"/&gt;
 *         &lt;element name="ResultCode"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Success"/&gt;
 *               &lt;enumeration value="Failed"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ResultDetail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FailureDetailMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pivAuthenticationCertResult",
    "pivDigitalSignatureCertResult",
    "pivKeyManagementCertResult",
    "pivCardAuthenticationCertResult",
    "resultCode",
    "resultDetail",
    "failureDetailMessage"
})
@XmlRootElement(name = "CheckPivCardCertsResponse", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
public class CheckPivCardCertsResponse {

    @XmlElement(name = "PivAuthenticationCertResult", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    @XmlSchemaType(name = "string")
    protected CertificateCheckResultType pivAuthenticationCertResult;
    @XmlElement(name = "PivDigitalSignatureCertResult", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    @XmlSchemaType(name = "string")
    protected CertificateCheckResultType pivDigitalSignatureCertResult;
    @XmlElement(name = "PivKeyManagementCertResult", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    @XmlSchemaType(name = "string")
    protected CertificateCheckResultType pivKeyManagementCertResult;
    @XmlElement(name = "PivCardAuthenticationCertResult", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    @XmlSchemaType(name = "string")
    protected CertificateCheckResultType pivCardAuthenticationCertResult;
    @XmlElement(name = "ResultCode", namespace = "http://hspd12.hhs.gov/piv/binding/v1", required = true)
    protected String resultCode;
    @XmlElement(name = "ResultDetail", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected String resultDetail;
    @XmlElement(name = "FailureDetailMessage", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected String failureDetailMessage;

    /**
     * Gets the value of the pivAuthenticationCertResult property.
     * 
     * @return
     *     possible object is
     *     {@link CertificateCheckResultType }
     *     
     */
    public CertificateCheckResultType getPivAuthenticationCertResult() {
        return pivAuthenticationCertResult;
    }

    /**
     * Sets the value of the pivAuthenticationCertResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertificateCheckResultType }
     *     
     */
    public void setPivAuthenticationCertResult(CertificateCheckResultType value) {
        this.pivAuthenticationCertResult = value;
    }

    /**
     * Gets the value of the pivDigitalSignatureCertResult property.
     * 
     * @return
     *     possible object is
     *     {@link CertificateCheckResultType }
     *     
     */
    public CertificateCheckResultType getPivDigitalSignatureCertResult() {
        return pivDigitalSignatureCertResult;
    }

    /**
     * Sets the value of the pivDigitalSignatureCertResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertificateCheckResultType }
     *     
     */
    public void setPivDigitalSignatureCertResult(CertificateCheckResultType value) {
        this.pivDigitalSignatureCertResult = value;
    }

    /**
     * Gets the value of the pivKeyManagementCertResult property.
     * 
     * @return
     *     possible object is
     *     {@link CertificateCheckResultType }
     *     
     */
    public CertificateCheckResultType getPivKeyManagementCertResult() {
        return pivKeyManagementCertResult;
    }

    /**
     * Sets the value of the pivKeyManagementCertResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertificateCheckResultType }
     *     
     */
    public void setPivKeyManagementCertResult(CertificateCheckResultType value) {
        this.pivKeyManagementCertResult = value;
    }

    /**
     * Gets the value of the pivCardAuthenticationCertResult property.
     * 
     * @return
     *     possible object is
     *     {@link CertificateCheckResultType }
     *     
     */
    public CertificateCheckResultType getPivCardAuthenticationCertResult() {
        return pivCardAuthenticationCertResult;
    }

    /**
     * Sets the value of the pivCardAuthenticationCertResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertificateCheckResultType }
     *     
     */
    public void setPivCardAuthenticationCertResult(CertificateCheckResultType value) {
        this.pivCardAuthenticationCertResult = value;
    }

    /**
     * Gets the value of the resultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * Sets the value of the resultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultCode(String value) {
        this.resultCode = value;
    }

    /**
     * Gets the value of the resultDetail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultDetail() {
        return resultDetail;
    }

    /**
     * Sets the value of the resultDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultDetail(String value) {
        this.resultDetail = value;
    }

    /**
     * Gets the value of the failureDetailMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFailureDetailMessage() {
        return failureDetailMessage;
    }

    /**
     * Sets the value of the failureDetailMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFailureDetailMessage(String value) {
        this.failureDetailMessage = value;
    }

}
