//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ProcessingNotification" type="{http://hspd12.hhs.gov/piv/binding/v1}ProcessingNotificationType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="WarningNotification" type="{http://hspd12.hhs.gov/piv/binding/v1}ProcessingNotificationType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ErrorNotification" type="{http://hspd12.hhs.gov/piv/binding/v1}ProcessingNotificationType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ResultCode"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Success"/&gt;
 *               &lt;enumeration value="ErrorDetected"/&gt;
 *               &lt;enumeration value="Failed"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FailureDetailMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "processingNotification",
    "warningNotification",
    "errorNotification",
    "resultCode",
    "failureDetailMessage"
})
@XmlRootElement(name = "CommitBindExternalCardResponse", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
public class CommitBindExternalCardResponse {

    @XmlElement(name = "ProcessingNotification", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected List<ProcessingNotificationType> processingNotification;
    @XmlElement(name = "WarningNotification", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected List<ProcessingNotificationType> warningNotification;
    @XmlElement(name = "ErrorNotification", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected List<ProcessingNotificationType> errorNotification;
    @XmlElement(name = "ResultCode", namespace = "http://hspd12.hhs.gov/piv/binding/v1", required = true)
    protected String resultCode;
    @XmlElement(name = "FailureDetailMessage", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected String failureDetailMessage;

    /**
     * Gets the value of the processingNotification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processingNotification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessingNotification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessingNotificationType }
     * 
     * 
     */
    public List<ProcessingNotificationType> getProcessingNotification() {
        if (processingNotification == null) {
            processingNotification = new ArrayList<ProcessingNotificationType>();
        }
        return this.processingNotification;
    }

    /**
     * Gets the value of the warningNotification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the warningNotification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWarningNotification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessingNotificationType }
     * 
     * 
     */
    public List<ProcessingNotificationType> getWarningNotification() {
        if (warningNotification == null) {
            warningNotification = new ArrayList<ProcessingNotificationType>();
        }
        return this.warningNotification;
    }

    /**
     * Gets the value of the errorNotification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the errorNotification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErrorNotification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessingNotificationType }
     * 
     * 
     */
    public List<ProcessingNotificationType> getErrorNotification() {
        if (errorNotification == null) {
            errorNotification = new ArrayList<ProcessingNotificationType>();
        }
        return this.errorNotification;
    }

    /**
     * Gets the value of the resultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * Sets the value of the resultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultCode(String value) {
        this.resultCode = value;
    }

    /**
     * Gets the value of the failureDetailMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFailureDetailMessage() {
        return failureDetailMessage;
    }

    /**
     * Sets the value of the failureDetailMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFailureDetailMessage(String value) {
        this.failureDetailMessage = value;
    }

}
