//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComponentCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ComponentCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;maxLength value="20"/&gt;
 *     &lt;enumeration value="OA"/&gt;
 *     &lt;enumeration value="CCSQ"/&gt;
 *     &lt;enumeration value="CCIIO"/&gt;
 *     &lt;enumeration value="CM"/&gt;
 *     &lt;enumeration value="CMCS"/&gt;
 *     &lt;enumeration value="CPI"/&gt;
 *     &lt;enumeration value="CMMI"/&gt;
 *     &lt;enumeration value="CFMFFSO"/&gt;
 *     &lt;enumeration value="CMCHO"/&gt;
 *     &lt;enumeration value="CMHPO"/&gt;
 *     &lt;enumeration value="CQISCO"/&gt;
 *     &lt;enumeration value="FCHCO"/&gt;
 *     &lt;enumeration value="OACT"/&gt;
 *     &lt;enumeration value="OAGM"/&gt;
 *     &lt;enumeration value="OC"/&gt;
 *     &lt;enumeration value="OEDA"/&gt;
 *     &lt;enumeration value="OEOCR"/&gt;
 *     &lt;enumeration value="OFM"/&gt;
 *     &lt;enumeration value="OHI"/&gt;
 *     &lt;enumeration value="OHC"/&gt;
 *     &lt;enumeration value="OMH"/&gt;
 *     &lt;enumeration value="OSORA"/&gt;
 *     &lt;enumeration value="OIT"/&gt;
 *     &lt;enumeration value="OL"/&gt;
 *     &lt;enumeration value="OSSO"/&gt;
 *     &lt;enumeration value="OTHER"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ComponentCodeType")
@XmlEnum
public enum ComponentCodeType {


    /**
     * Office of Administrator
     * 
     */
    OA,

    /**
     * Centers for Clinical Standards and Quality
     * 
     */
    CCSQ,

    /**
     * Center for Consumer Information and Insurance Oversight
     * 
     */
    CCIIO,

    /**
     * Center for Medicare
     * 
     */
    CM,

    /**
     * Center for Medicare and CHIP Services
     * 
     */
    CMCS,

    /**
     * Center for Program Integrity
     * 
     */
    CPI,

    /**
     * Center for Medicare and Medicare Innovation
     * 
     */
    CMMI,

    /**
     * Consortium for Financial Management and Fee for Service Operations
     * 
     */
    CFMFFSO,

    /**
     * Consortium for Medicaid and Children's Health Operations
     * 
     */
    CMCHO,

    /**
     * Consortium for Medicare Health Plans Operations
     * 
     */
    CMHPO,

    /**
     * Consortium for Quality Improvement and Survey & Certification Operations
     * 
     */
    CQISCO,

    /**
     * Federal Coordinated Health Care Office
     * 
     */
    FCHCO,

    /**
     * Office of the Actuary
     * 
     */
    OACT,

    /**
     * Office of Acquisitions and Grants Management
     * 
     */
    OAGM,

    /**
     * Office of Communications
     * 
     */
    OC,

    /**
     * Office of Enterprise Data and Analytics
     * 
     */
    OEDA,

    /**
     * Office of Equal Opportunities and Civil Rights
     * 
     */
    OEOCR,

    /**
     * Office of Financial Management
     * 
     */
    OFM,

    /**
     * Offices of Hearings and Inquiries
     * 
     */
    OHI,

    /**
     * Office of Human Capital
     * 
     */
    OHC,

    /**
     * Office of Minority Health
     * 
     */
    OMH,

    /**
     * Office of Strategic Operations and Regulatory Affairs
     * 
     */
    OSORA,

    /**
     * Office of Information Technology
     * 
     */
    OIT,

    /**
     * Office of Legislation
     * 
     */
    OL,

    /**
     * Office of Support Services and Operations
     * 
     */
    OSSO,

    /**
     * Other
     * 
     */
    OTHER;

    public String value() {
        return name();
    }

    public static ComponentCodeType fromValue(String v) {
        return valueOf(v);
    }

}
