//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				This type defines information which may be retrieved for an IDMS 
 * 				event subscription.
 * 			
 * 
 * <p>Java class for EventSubscriptionInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventSubscriptionInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EventSubscriptionId"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="20"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="EventNotifyType" type="{http://hspd12.hhs.gov/federated/enrollment/v1}IdmsEventNotifyType"/&gt;
 *         &lt;element name="agencyAcronym" type="{http://hspd12.hhs.gov/federated/enrollment/v1}OpdivCodeType"/&gt;
 *         &lt;element name="NotifyURL" type="{http://hspd12.hhs.gov/federated/enrollment/v1}EventNotifyURLType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventSubscriptionInfoType", propOrder = {
    "eventSubscriptionId",
    "eventNotifyType",
    "agencyAcronym",
    "notifyURL"
})
public class EventSubscriptionInfoType {

    @XmlElement(name = "EventSubscriptionId", required = true)
    protected String eventSubscriptionId;
    @XmlElement(name = "EventNotifyType", required = true)
    @XmlSchemaType(name = "string")
    protected IdmsEventNotifyType eventNotifyType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected OpdivCodeType agencyAcronym;
    @XmlElement(name = "NotifyURL", required = true)
    protected String notifyURL;

    /**
     * Gets the value of the eventSubscriptionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventSubscriptionId() {
        return eventSubscriptionId;
    }

    /**
     * Sets the value of the eventSubscriptionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventSubscriptionId(String value) {
        this.eventSubscriptionId = value;
    }

    /**
     * Gets the value of the eventNotifyType property.
     * 
     * @return
     *     possible object is
     *     {@link IdmsEventNotifyType }
     *     
     */
    public IdmsEventNotifyType getEventNotifyType() {
        return eventNotifyType;
    }

    /**
     * Sets the value of the eventNotifyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdmsEventNotifyType }
     *     
     */
    public void setEventNotifyType(IdmsEventNotifyType value) {
        this.eventNotifyType = value;
    }

    /**
     * Gets the value of the agencyAcronym property.
     * 
     * @return
     *     possible object is
     *     {@link OpdivCodeType }
     *     
     */
    public OpdivCodeType getAgencyAcronym() {
        return agencyAcronym;
    }

    /**
     * Sets the value of the agencyAcronym property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpdivCodeType }
     *     
     */
    public void setAgencyAcronym(OpdivCodeType value) {
        this.agencyAcronym = value;
    }

    /**
     * Gets the value of the notifyURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotifyURL() {
        return notifyURL;
    }

    /**
     * Sets the value of the notifyURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotifyURL(String value) {
        this.notifyURL = value;
    }

}
