//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CardHolderFacialImageCbeff" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cardHolderFacialImageCbeff"
})
@XmlRootElement(name = "ExtractImageAsJpegRequest", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
public class ExtractImageAsJpegRequest {

    @XmlElement(name = "CardHolderFacialImageCbeff", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected byte[] cardHolderFacialImageCbeff;

    /**
     * Gets the value of the cardHolderFacialImageCbeff property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCardHolderFacialImageCbeff() {
        return cardHolderFacialImageCbeff;
    }

    /**
     * Sets the value of the cardHolderFacialImageCbeff property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCardHolderFacialImageCbeff(byte[] value) {
        this.cardHolderFacialImageCbeff = value;
    }

}
