//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IdmsEventNotifyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IdmsEventNotifyType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;maxLength value="40"/&gt;
 *     &lt;enumeration value="CardReady"/&gt;
 *     &lt;enumeration value="CardStateChanged"/&gt;
 *     &lt;enumeration value="ApplicantDataChanged"/&gt;
 *     &lt;enumeration value="EnrollmentCompleted"/&gt;
 *     &lt;enumeration value="ApplicantInfoSentToOPM"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "IdmsEventNotifyType")
@XmlEnum
public enum IdmsEventNotifyType {


    /**
     * Card ready for issuance
     * 
     */
    @XmlEnumValue("CardReady")
    CARD_READY("CardReady"),

    /**
     * Card state changed
     * 
     */
    @XmlEnumValue("CardStateChanged")
    CARD_STATE_CHANGED("CardStateChanged"),

    /**
     * Applicant data changed
     * 
     */
    @XmlEnumValue("ApplicantDataChanged")
    APPLICANT_DATA_CHANGED("ApplicantDataChanged"),

    /**
     * Enrollment completed
     * 
     */
    @XmlEnumValue("EnrollmentCompleted")
    ENROLLMENT_COMPLETED("EnrollmentCompleted"),

    /**
     * Applicant info has been sent to OPM for review
     * 
     */
    @XmlEnumValue("ApplicantInfoSentToOPM")
    APPLICANT_INFO_SENT_TO_OPM("ApplicantInfoSentToOPM");
    private final String value;

    IdmsEventNotifyType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IdmsEventNotifyType fromValue(String v) {
        for (IdmsEventNotifyType c: IdmsEventNotifyType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
