//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.hhs.induction.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PersonInformationTypeSalutation_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "Salutation");
    private final static QName _PersonInformationTypeMiddleName_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "MiddleName");
    private final static QName _PersonInformationTypeNameSuffix_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "NameSuffix");
    private final static QName _PersonInformationTypeWorkAddress1_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "WorkAddress1");
    private final static QName _PersonInformationTypeWorkAddress2_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "WorkAddress2");
    private final static QName _PersonInformationTypeWorkAddress3_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "WorkAddress3");
    private final static QName _PersonInformationTypeWorkCity_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "WorkCity");
    private final static QName _PersonInformationTypeWorkState_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "WorkState");
    private final static QName _PersonInformationTypeWorkPostalCode_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "WorkPostalCode");
    private final static QName _PersonInformationTypeWorkCountry_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "WorkCountry");
    private final static QName _PersonInformationTypeWorkPhone_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "WorkPhone");
    private final static QName _PersonInformationTypeAlternatePhone_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "AlternatePhone");
    private final static QName _PacsFingerPrintInfoTypePrintDataFormat_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "PrintDataFormat");
    private final static QName _PacsFingerPrintInfoTypePrintData_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "PrintData");
    private final static QName _PacsFacialImageInfoTypeImageData_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "ImageData");
    private final static QName _PacsFacialImageInfoTypeThumbNailData_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "ThumbNailData");
    private final static QName _PacsCardIdentifiersTypeFASCN_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "FASCN");
    private final static QName _PacsCardIdentifiersTypePacsCardIdentifier_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "PacsCardIdentifier");
    private final static QName _PacsCardInformationTypeCardId_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "CardId");
    private final static QName _PacsCardInformationTypeFacialImage_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "FacialImage");
    private final static QName _PacsCardInformationTypeFingerPrints_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "FingerPrints");
    private final static QName _PacsPersonInfoDataTypePrefix_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "Prefix");
    private final static QName _PacsPersonInfoDataTypeFirstName_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "FirstName");
    private final static QName _PacsPersonInfoDataTypeMiddleName_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "MiddleName");
    private final static QName _PacsPersonInfoDataTypeLastName_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "LastName");
    private final static QName _PacsPersonInfoDataTypeGenerationQualifier_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "GenerationQualifier");
    private final static QName _PacsPersonInfoDataTypeNameSuffix_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "NameSuffix");
    private final static QName _PacsPersonInfoDataTypeDOB_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "DOB");
    private final static QName _PacsPersonInfoDataTypeCityOfBirth_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "CityOfBirth");
    private final static QName _PacsPersonInfoDataTypeStateOfBirth_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "StateOfBirth");
    private final static QName _PacsPersonInfoDataTypeCountryOfBirth_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "CountryOfBirth");
    private final static QName _PacsPersonInfoDataTypeCountryOfCitizenship_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "CountryOfCitizenship");
    private final static QName _PacsPersonInfoDataTypeVisaNumber_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "VisaNumber");
    private final static QName _PacsPersonInfoDataTypeARN_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "ARN");
    private final static QName _PacsPersonInfoDataTypeForeignID_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "ForeignID");
    private final static QName _PacsPersonInfoDataTypePositionTitle_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "PositionTitle");
    private final static QName _PacsPersonInfoDataTypePositionSensitivity_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "PositionSensitivity");
    private final static QName _PacsPersonInfoDataTypeEmergencyResponder_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "EmergencyResponder");
    private final static QName _PacsPersonInfoDataTypeCredentialCategory_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "CredentialCategory");
    private final static QName _PacsPersonInfoDataTypeOrganization_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "Organization");
    private final static QName _PacsPersonInfoDataTypeOPDIV_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "OPDIV");
    private final static QName _PacsPersonInfoDataTypeAffiliationCode_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "AffiliationCode");
    private final static QName _PacsPersonInfoDataTypeEmployerName_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "EmployerName");
    private final static QName _PacsPersonInfoDataTypeWorkLocationCode_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "WorkLocationCode");
    private final static QName _PacsPersonInfoDataTypeWorkPhone_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "WorkPhone");
    private final static QName _PacsPersonInfoDataTypeWorkPhoneExtension_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "WorkPhoneExtension");
    private final static QName _PacsPersonInfoDataTypeCostCenter_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "CostCenter");
    private final static QName _PacsPersonInfoDataTypeSubAgency_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "SubAgency");
    private final static QName _PacsPersonInfoDataTypePrimaryEmailAddress_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "PrimaryEmailAddress");
    private final static QName _PacsPersonInfoDataTypeAlternateEmailAddress_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "AlternateEmailAddress");
    private final static QName _PacsPersonInfoDataTypeUPN_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "UPN");
    private final static QName _PacsPersonIdentifiersTypeHHSID_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "HHSID");
    private final static QName _PacsPersonIdentifiersTypeEmployeeID_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "EmployeeID");
    private final static QName _InductionDataTypeCopsAgency_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "CopsAgency");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.hhs.induction.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PacsGetNodeStatusResponse }
     * 
     */
    public PacsGetNodeStatusResponse createPacsGetNodeStatusResponse() {
        return new PacsGetNodeStatusResponse();
    }

    /**
     * Create an instance of {@link IdmPersonInfoType }
     * 
     */
    public IdmPersonInfoType createIdmPersonInfoType() {
        return new IdmPersonInfoType();
    }

    /**
     * Create an instance of {@link IdmPersonInfoType.IdentityInfo }
     * 
     */
    public IdmPersonInfoType.IdentityInfo createIdmPersonInfoTypeIdentityInfo() {
        return new IdmPersonInfoType.IdentityInfo();
    }

    /**
     * Create an instance of {@link InductPersonRequest }
     * 
     */
    public InductPersonRequest createInductPersonRequest() {
        return new InductPersonRequest();
    }

    /**
     * Create an instance of {@link TransactionHeaderType }
     * 
     */
    public TransactionHeaderType createTransactionHeaderType() {
        return new TransactionHeaderType();
    }

    /**
     * Create an instance of {@link InductPersonApplicantDataType }
     * 
     */
    public InductPersonApplicantDataType createInductPersonApplicantDataType() {
        return new InductPersonApplicantDataType();
    }

    /**
     * Create an instance of {@link InductPersonIncRequest }
     * 
     */
    public InductPersonIncRequest createInductPersonIncRequest() {
        return new InductPersonIncRequest();
    }

    /**
     * Create an instance of {@link InductionDataType }
     * 
     */
    public InductionDataType createInductionDataType() {
        return new InductionDataType();
    }

    /**
     * Create an instance of {@link InductPersonResponse }
     * 
     */
    public InductPersonResponse createInductPersonResponse() {
        return new InductPersonResponse();
    }

    /**
     * Create an instance of {@link InductPersonResultType }
     * 
     */
    public InductPersonResultType createInductPersonResultType() {
        return new InductPersonResultType();
    }

    /**
     * Create an instance of {@link ReadInductionDataRequest }
     * 
     */
    public ReadInductionDataRequest createReadInductionDataRequest() {
        return new ReadInductionDataRequest();
    }

    /**
     * Create an instance of {@link ReadInductionDataResponse }
     * 
     */
    public ReadInductionDataResponse createReadInductionDataResponse() {
        return new ReadInductionDataResponse();
    }

    /**
     * Create an instance of {@link UpdateInductionDataRequest }
     * 
     */
    public UpdateInductionDataRequest createUpdateInductionDataRequest() {
        return new UpdateInductionDataRequest();
    }

    /**
     * Create an instance of {@link UpdateInductionDataResponse }
     * 
     */
    public UpdateInductionDataResponse createUpdateInductionDataResponse() {
        return new UpdateInductionDataResponse();
    }

    /**
     * Create an instance of {@link ReadFacialImageRequest }
     * 
     */
    public ReadFacialImageRequest createReadFacialImageRequest() {
        return new ReadFacialImageRequest();
    }

    /**
     * Create an instance of {@link ReadFacialImageResponse }
     * 
     */
    public ReadFacialImageResponse createReadFacialImageResponse() {
        return new ReadFacialImageResponse();
    }

    /**
     * Create an instance of {@link FacialImageDataType }
     * 
     */
    public FacialImageDataType createFacialImageDataType() {
        return new FacialImageDataType();
    }

    /**
     * Create an instance of {@link ReservePersonIdentifierRequest }
     * 
     */
    public ReservePersonIdentifierRequest createReservePersonIdentifierRequest() {
        return new ReservePersonIdentifierRequest();
    }

    /**
     * Create an instance of {@link ReservePersonIdentifierResponse }
     * 
     */
    public ReservePersonIdentifierResponse createReservePersonIdentifierResponse() {
        return new ReservePersonIdentifierResponse();
    }

    /**
     * Create an instance of {@link MatchPersonRequest }
     * 
     */
    public MatchPersonRequest createMatchPersonRequest() {
        return new MatchPersonRequest();
    }

    /**
     * Create an instance of {@link MatchPersonSearchData }
     * 
     */
    public MatchPersonSearchData createMatchPersonSearchData() {
        return new MatchPersonSearchData();
    }

    /**
     * Create an instance of {@link MatchPersonResponse }
     * 
     */
    public MatchPersonResponse createMatchPersonResponse() {
        return new MatchPersonResponse();
    }

    /**
     * Create an instance of {@link MatchPersonResultsData }
     * 
     */
    public MatchPersonResultsData createMatchPersonResultsData() {
        return new MatchPersonResultsData();
    }

    /**
     * Create an instance of {@link GetApplicantProcessingStateRequest }
     * 
     */
    public GetApplicantProcessingStateRequest createGetApplicantProcessingStateRequest() {
        return new GetApplicantProcessingStateRequest();
    }

    /**
     * Create an instance of {@link GetApplicantProcessingStateResponse }
     * 
     */
    public GetApplicantProcessingStateResponse createGetApplicantProcessingStateResponse() {
        return new GetApplicantProcessingStateResponse();
    }

    /**
     * Create an instance of {@link MissingInductionDataInfoType }
     * 
     */
    public MissingInductionDataInfoType createMissingInductionDataInfoType() {
        return new MissingInductionDataInfoType();
    }

    /**
     * Create an instance of {@link DeactivateApplicantRequest }
     * 
     */
    public DeactivateApplicantRequest createDeactivateApplicantRequest() {
        return new DeactivateApplicantRequest();
    }

    /**
     * Create an instance of {@link DeactivateApplicantResponse }
     * 
     */
    public DeactivateApplicantResponse createDeactivateApplicantResponse() {
        return new DeactivateApplicantResponse();
    }

    /**
     * Create an instance of {@link GetHHSIDRequest }
     * 
     */
    public GetHHSIDRequest createGetHHSIDRequest() {
        return new GetHHSIDRequest();
    }

    /**
     * Create an instance of {@link GetHHSIDResponse }
     * 
     */
    public GetHHSIDResponse createGetHHSIDResponse() {
        return new GetHHSIDResponse();
    }

    /**
     * Create an instance of {@link GetHHSIdDataType }
     * 
     */
    public GetHHSIdDataType createGetHHSIdDataType() {
        return new GetHHSIdDataType();
    }

    /**
     * Create an instance of {@link RegisterCopsApplicantRequest }
     * 
     */
    public RegisterCopsApplicantRequest createRegisterCopsApplicantRequest() {
        return new RegisterCopsApplicantRequest();
    }

    /**
     * Create an instance of {@link RegisterCopsApplicantResponse }
     * 
     */
    public RegisterCopsApplicantResponse createRegisterCopsApplicantResponse() {
        return new RegisterCopsApplicantResponse();
    }

    /**
     * Create an instance of {@link UnregisterCopsApplicantRequest }
     * 
     */
    public UnregisterCopsApplicantRequest createUnregisterCopsApplicantRequest() {
        return new UnregisterCopsApplicantRequest();
    }

    /**
     * Create an instance of {@link UnregisterCopsApplicantResponse }
     * 
     */
    public UnregisterCopsApplicantResponse createUnregisterCopsApplicantResponse() {
        return new UnregisterCopsApplicantResponse();
    }

    /**
     * Create an instance of {@link CheckCopsRegistrationStatusRequest }
     * 
     */
    public CheckCopsRegistrationStatusRequest createCheckCopsRegistrationStatusRequest() {
        return new CheckCopsRegistrationStatusRequest();
    }

    /**
     * Create an instance of {@link CheckCopsRegistrationStatusResponse }
     * 
     */
    public CheckCopsRegistrationStatusResponse createCheckCopsRegistrationStatusResponse() {
        return new CheckCopsRegistrationStatusResponse();
    }

    /**
     * Create an instance of {@link SyncGetApplicantDataHashRequest }
     * 
     */
    public SyncGetApplicantDataHashRequest createSyncGetApplicantDataHashRequest() {
        return new SyncGetApplicantDataHashRequest();
    }

    /**
     * Create an instance of {@link PersonIdRangeType }
     * 
     */
    public PersonIdRangeType createPersonIdRangeType() {
        return new PersonIdRangeType();
    }

    /**
     * Create an instance of {@link SyncGetApplicantDataHashResponse }
     * 
     */
    public SyncGetApplicantDataHashResponse createSyncGetApplicantDataHashResponse() {
        return new SyncGetApplicantDataHashResponse();
    }

    /**
     * Create an instance of {@link SyncApplicantDataHashType }
     * 
     */
    public SyncApplicantDataHashType createSyncApplicantDataHashType() {
        return new SyncApplicantDataHashType();
    }

    /**
     * Create an instance of {@link SyncGetApplicantInfoHashRequest }
     * 
     */
    public SyncGetApplicantInfoHashRequest createSyncGetApplicantInfoHashRequest() {
        return new SyncGetApplicantInfoHashRequest();
    }

    /**
     * Create an instance of {@link SyncGetApplicantInfoHashResponse }
     * 
     */
    public SyncGetApplicantInfoHashResponse createSyncGetApplicantInfoHashResponse() {
        return new SyncGetApplicantInfoHashResponse();
    }

    /**
     * Create an instance of {@link SyncApplicantInfoHashType }
     * 
     */
    public SyncApplicantInfoHashType createSyncApplicantInfoHashType() {
        return new SyncApplicantInfoHashType();
    }

    /**
     * Create an instance of {@link SyncGetApplicantDataDiffRequest }
     * 
     */
    public SyncGetApplicantDataDiffRequest createSyncGetApplicantDataDiffRequest() {
        return new SyncGetApplicantDataDiffRequest();
    }

    /**
     * Create an instance of {@link SyncGetApplicantDataDiffResponse }
     * 
     */
    public SyncGetApplicantDataDiffResponse createSyncGetApplicantDataDiffResponse() {
        return new SyncGetApplicantDataDiffResponse();
    }

    /**
     * Create an instance of {@link SyncGetApplicantDataDiffResultType }
     * 
     */
    public SyncGetApplicantDataDiffResultType createSyncGetApplicantDataDiffResultType() {
        return new SyncGetApplicantDataDiffResultType();
    }

    /**
     * Create an instance of {@link SyncSetOpdivHashedFieldsRequest }
     * 
     */
    public SyncSetOpdivHashedFieldsRequest createSyncSetOpdivHashedFieldsRequest() {
        return new SyncSetOpdivHashedFieldsRequest();
    }

    /**
     * Create an instance of {@link SyncSetOpdivHashedFieldsResponse }
     * 
     */
    public SyncSetOpdivHashedFieldsResponse createSyncSetOpdivHashedFieldsResponse() {
        return new SyncSetOpdivHashedFieldsResponse();
    }

    /**
     * Create an instance of {@link CardTrackingUpdateRequest }
     * 
     */
    public CardTrackingUpdateRequest createCardTrackingUpdateRequest() {
        return new CardTrackingUpdateRequest();
    }

    /**
     * Create an instance of {@link CardTrackingUpdateResponse }
     * 
     */
    public CardTrackingUpdateResponse createCardTrackingUpdateResponse() {
        return new CardTrackingUpdateResponse();
    }

    /**
     * Create an instance of {@link GetCardTrackingHistoryRequest }
     * 
     */
    public GetCardTrackingHistoryRequest createGetCardTrackingHistoryRequest() {
        return new GetCardTrackingHistoryRequest();
    }

    /**
     * Create an instance of {@link GetCardTrackingHistoryResponse }
     * 
     */
    public GetCardTrackingHistoryResponse createGetCardTrackingHistoryResponse() {
        return new GetCardTrackingHistoryResponse();
    }

    /**
     * Create an instance of {@link CardTrackingHistoryEventType }
     * 
     */
    public CardTrackingHistoryEventType createCardTrackingHistoryEventType() {
        return new CardTrackingHistoryEventType();
    }

    /**
     * Create an instance of {@link CardRenewalRequiredRequest }
     * 
     */
    public CardRenewalRequiredRequest createCardRenewalRequiredRequest() {
        return new CardRenewalRequiredRequest();
    }

    /**
     * Create an instance of {@link CardRenewalRequiredResponse }
     * 
     */
    public CardRenewalRequiredResponse createCardRenewalRequiredResponse() {
        return new CardRenewalRequiredResponse();
    }

    /**
     * Create an instance of {@link CardReissueRequiredRequest }
     * 
     */
    public CardReissueRequiredRequest createCardReissueRequiredRequest() {
        return new CardReissueRequiredRequest();
    }

    /**
     * Create an instance of {@link CardReissueRequiredResponse }
     * 
     */
    public CardReissueRequiredResponse createCardReissueRequiredResponse() {
        return new CardReissueRequiredResponse();
    }

    /**
     * Create an instance of {@link PIVTerminationRequest }
     * 
     */
    public PIVTerminationRequest createPIVTerminationRequest() {
        return new PIVTerminationRequest();
    }

    /**
     * Create an instance of {@link PIVTerminationResponse }
     * 
     */
    public PIVTerminationResponse createPIVTerminationResponse() {
        return new PIVTerminationResponse();
    }

    /**
     * Create an instance of {@link PIVReactivationRequest }
     * 
     */
    public PIVReactivationRequest createPIVReactivationRequest() {
        return new PIVReactivationRequest();
    }

    /**
     * Create an instance of {@link PIVReactivationResponse }
     * 
     */
    public PIVReactivationResponse createPIVReactivationResponse() {
        return new PIVReactivationResponse();
    }

    /**
     * Create an instance of {@link CreateBadgeRequest }
     * 
     */
    public CreateBadgeRequest createCreateBadgeRequest() {
        return new CreateBadgeRequest();
    }

    /**
     * Create an instance of {@link CreateBadgeResponse }
     * 
     */
    public CreateBadgeResponse createCreateBadgeResponse() {
        return new CreateBadgeResponse();
    }

    /**
     * Create an instance of {@link GetIssuedCardInfoRequest }
     * 
     */
    public GetIssuedCardInfoRequest createGetIssuedCardInfoRequest() {
        return new GetIssuedCardInfoRequest();
    }

    /**
     * Create an instance of {@link GetIssuedCardInfoResponse }
     * 
     */
    public GetIssuedCardInfoResponse createGetIssuedCardInfoResponse() {
        return new GetIssuedCardInfoResponse();
    }

    /**
     * Create an instance of {@link CHUIDDataFieldsType }
     * 
     */
    public CHUIDDataFieldsType createCHUIDDataFieldsType() {
        return new CHUIDDataFieldsType();
    }

    /**
     * Create an instance of {@link ReissueExistentCardRequest }
     * 
     */
    public ReissueExistentCardRequest createReissueExistentCardRequest() {
        return new ReissueExistentCardRequest();
    }

    /**
     * Create an instance of {@link ReissueExistentCardResponse }
     * 
     */
    public ReissueExistentCardResponse createReissueExistentCardResponse() {
        return new ReissueExistentCardResponse();
    }

    /**
     * Create an instance of {@link CheckCardRequest }
     * 
     */
    public CheckCardRequest createCheckCardRequest() {
        return new CheckCardRequest();
    }

    /**
     * Create an instance of {@link CheckCardResponse }
     * 
     */
    public CheckCardResponse createCheckCardResponse() {
        return new CheckCardResponse();
    }

    /**
     * Create an instance of {@link SubscribeCardEventsRequest }
     * 
     */
    public SubscribeCardEventsRequest createSubscribeCardEventsRequest() {
        return new SubscribeCardEventsRequest();
    }

    /**
     * Create an instance of {@link SubscribeCardEventsResponse }
     * 
     */
    public SubscribeCardEventsResponse createSubscribeCardEventsResponse() {
        return new SubscribeCardEventsResponse();
    }

    /**
     * Create an instance of {@link UnSubscribeCardEventsRequest }
     * 
     */
    public UnSubscribeCardEventsRequest createUnSubscribeCardEventsRequest() {
        return new UnSubscribeCardEventsRequest();
    }

    /**
     * Create an instance of {@link UnSubscribeCardEventsResponse }
     * 
     */
    public UnSubscribeCardEventsResponse createUnSubscribeCardEventsResponse() {
        return new UnSubscribeCardEventsResponse();
    }

    /**
     * Create an instance of {@link CardEventNotifyRequest }
     * 
     */
    public CardEventNotifyRequest createCardEventNotifyRequest() {
        return new CardEventNotifyRequest();
    }

    /**
     * Create an instance of {@link CardReadyNotifyType }
     * 
     */
    public CardReadyNotifyType createCardReadyNotifyType() {
        return new CardReadyNotifyType();
    }

    /**
     * Create an instance of {@link CardStateChangeNotifyType }
     * 
     */
    public CardStateChangeNotifyType createCardStateChangeNotifyType() {
        return new CardStateChangeNotifyType();
    }

    /**
     * Create an instance of {@link CardEventNotifyResponse }
     * 
     */
    public CardEventNotifyResponse createCardEventNotifyResponse() {
        return new CardEventNotifyResponse();
    }

    /**
     * Create an instance of {@link ApplicantDataChangeNotifyRequest }
     * 
     */
    public ApplicantDataChangeNotifyRequest createApplicantDataChangeNotifyRequest() {
        return new ApplicantDataChangeNotifyRequest();
    }

    /**
     * Create an instance of {@link ApplicantDataChangeNotifyResponse }
     * 
     */
    public ApplicantDataChangeNotifyResponse createApplicantDataChangeNotifyResponse() {
        return new ApplicantDataChangeNotifyResponse();
    }

    /**
     * Create an instance of {@link EnrollmentCompletedNotifyRequest }
     * 
     */
    public EnrollmentCompletedNotifyRequest createEnrollmentCompletedNotifyRequest() {
        return new EnrollmentCompletedNotifyRequest();
    }

    /**
     * Create an instance of {@link EnrollmentCompletedNotifyResponse }
     * 
     */
    public EnrollmentCompletedNotifyResponse createEnrollmentCompletedNotifyResponse() {
        return new EnrollmentCompletedNotifyResponse();
    }

    /**
     * Create an instance of {@link ApplicantInfoSentToOpmNotifyRequest }
     * 
     */
    public ApplicantInfoSentToOpmNotifyRequest createApplicantInfoSentToOpmNotifyRequest() {
        return new ApplicantInfoSentToOpmNotifyRequest();
    }

    /**
     * Create an instance of {@link ApplicantInfoSentToOpmNotifyResponse }
     * 
     */
    public ApplicantInfoSentToOpmNotifyResponse createApplicantInfoSentToOpmNotifyResponse() {
        return new ApplicantInfoSentToOpmNotifyResponse();
    }

    /**
     * Create an instance of {@link SubscribeIdmsEventsRequest }
     * 
     */
    public SubscribeIdmsEventsRequest createSubscribeIdmsEventsRequest() {
        return new SubscribeIdmsEventsRequest();
    }

    /**
     * Create an instance of {@link SubscribeIdmsEventsResponse }
     * 
     */
    public SubscribeIdmsEventsResponse createSubscribeIdmsEventsResponse() {
        return new SubscribeIdmsEventsResponse();
    }

    /**
     * Create an instance of {@link UnSubscribeIdmsEventsRequest }
     * 
     */
    public UnSubscribeIdmsEventsRequest createUnSubscribeIdmsEventsRequest() {
        return new UnSubscribeIdmsEventsRequest();
    }

    /**
     * Create an instance of {@link UnSubscribeIdmsEventsResponse }
     * 
     */
    public UnSubscribeIdmsEventsResponse createUnSubscribeIdmsEventsResponse() {
        return new UnSubscribeIdmsEventsResponse();
    }

    /**
     * Create an instance of {@link QuerySubscribedIdmsEventsRequest }
     * 
     */
    public QuerySubscribedIdmsEventsRequest createQuerySubscribedIdmsEventsRequest() {
        return new QuerySubscribedIdmsEventsRequest();
    }

    /**
     * Create an instance of {@link QuerySubscribedIdmsEventsResponse }
     * 
     */
    public QuerySubscribedIdmsEventsResponse createQuerySubscribedIdmsEventsResponse() {
        return new QuerySubscribedIdmsEventsResponse();
    }

    /**
     * Create an instance of {@link EventSubscriptionInfoType }
     * 
     */
    public EventSubscriptionInfoType createEventSubscriptionInfoType() {
        return new EventSubscriptionInfoType();
    }

    /**
     * Create an instance of {@link GetPacsPersonDataRequest }
     * 
     */
    public GetPacsPersonDataRequest createGetPacsPersonDataRequest() {
        return new GetPacsPersonDataRequest();
    }

    /**
     * Create an instance of {@link PacsPersonIdentifiersType }
     * 
     */
    public PacsPersonIdentifiersType createPacsPersonIdentifiersType() {
        return new PacsPersonIdentifiersType();
    }

    /**
     * Create an instance of {@link GetPacsPersonDataResponse }
     * 
     */
    public GetPacsPersonDataResponse createGetPacsPersonDataResponse() {
        return new GetPacsPersonDataResponse();
    }

    /**
     * Create an instance of {@link PacsPersonInfoDataType }
     * 
     */
    public PacsPersonInfoDataType createPacsPersonInfoDataType() {
        return new PacsPersonInfoDataType();
    }

    /**
     * Create an instance of {@link PacsCardInformationType }
     * 
     */
    public PacsCardInformationType createPacsCardInformationType() {
        return new PacsCardInformationType();
    }

    /**
     * Create an instance of {@link SetPacsPersonDataRequest }
     * 
     */
    public SetPacsPersonDataRequest createSetPacsPersonDataRequest() {
        return new SetPacsPersonDataRequest();
    }

    /**
     * Create an instance of {@link PacsCardIdentifiersType }
     * 
     */
    public PacsCardIdentifiersType createPacsCardIdentifiersType() {
        return new PacsCardIdentifiersType();
    }

    /**
     * Create an instance of {@link SetPacsPersonDataResponse }
     * 
     */
    public SetPacsPersonDataResponse createSetPacsPersonDataResponse() {
        return new SetPacsPersonDataResponse();
    }

    /**
     * Create an instance of {@link PacsPendingOperationCompleteNotifyRequest }
     * 
     */
    public PacsPendingOperationCompleteNotifyRequest createPacsPendingOperationCompleteNotifyRequest() {
        return new PacsPendingOperationCompleteNotifyRequest();
    }

    /**
     * Create an instance of {@link PacsPendingOperationResultType }
     * 
     */
    public PacsPendingOperationResultType createPacsPendingOperationResultType() {
        return new PacsPendingOperationResultType();
    }

    /**
     * Create an instance of {@link PacsPendingOperationCompleteNotifyResponse }
     * 
     */
    public PacsPendingOperationCompleteNotifyResponse createPacsPendingOperationCompleteNotifyResponse() {
        return new PacsPendingOperationCompleteNotifyResponse();
    }

    /**
     * Create an instance of {@link PacsGetNodeStatusRequest }
     * 
     */
    public PacsGetNodeStatusRequest createPacsGetNodeStatusRequest() {
        return new PacsGetNodeStatusRequest();
    }

    /**
     * Create an instance of {@link PacsGetNodeStatusResponse.ResultXml }
     * 
     */
    public PacsGetNodeStatusResponse.ResultXml createPacsGetNodeStatusResponseResultXml() {
        return new PacsGetNodeStatusResponse.ResultXml();
    }

    /**
     * Create an instance of {@link ForeignNationalIdInfoType }
     * 
     */
    public ForeignNationalIdInfoType createForeignNationalIdInfoType() {
        return new ForeignNationalIdInfoType();
    }

    /**
     * Create an instance of {@link ForeignPlaceOfBirthInfoType }
     * 
     */
    public ForeignPlaceOfBirthInfoType createForeignPlaceOfBirthInfoType() {
        return new ForeignPlaceOfBirthInfoType();
    }

    /**
     * Create an instance of {@link ApplicantAlternateUIDType }
     * 
     */
    public ApplicantAlternateUIDType createApplicantAlternateUIDType() {
        return new ApplicantAlternateUIDType();
    }

    /**
     * Create an instance of {@link FASCNDataFieldsType }
     * 
     */
    public FASCNDataFieldsType createFASCNDataFieldsType() {
        return new FASCNDataFieldsType();
    }

    /**
     * Create an instance of {@link CardHistoryType }
     * 
     */
    public CardHistoryType createCardHistoryType() {
        return new CardHistoryType();
    }

    /**
     * Create an instance of {@link CardHistoryListType }
     * 
     */
    public CardHistoryListType createCardHistoryListType() {
        return new CardHistoryListType();
    }

    /**
     * Create an instance of {@link HHSInductPersonRequiredDataType }
     * 
     */
    public HHSInductPersonRequiredDataType createHHSInductPersonRequiredDataType() {
        return new HHSInductPersonRequiredDataType();
    }

    /**
     * Create an instance of {@link HHSInductPersonOptionalDataType }
     * 
     */
    public HHSInductPersonOptionalDataType createHHSInductPersonOptionalDataType() {
        return new HHSInductPersonOptionalDataType();
    }

    /**
     * Create an instance of {@link IdentificationInformationType }
     * 
     */
    public IdentificationInformationType createIdentificationInformationType() {
        return new IdentificationInformationType();
    }

    /**
     * Create an instance of {@link ApplicantFieldDifferenceType }
     * 
     */
    public ApplicantFieldDifferenceType createApplicantFieldDifferenceType() {
        return new ApplicantFieldDifferenceType();
    }

    /**
     * Create an instance of {@link PacsFacialImageInfoType }
     * 
     */
    public PacsFacialImageInfoType createPacsFacialImageInfoType() {
        return new PacsFacialImageInfoType();
    }

    /**
     * Create an instance of {@link PacsFingerPrintInfoType }
     * 
     */
    public PacsFingerPrintInfoType createPacsFingerPrintInfoType() {
        return new PacsFingerPrintInfoType();
    }

    /**
     * Create an instance of {@link GetPersonDataRequest }
     * 
     */
    public GetPersonDataRequest createGetPersonDataRequest() {
        return new GetPersonDataRequest();
    }

    /**
     * Create an instance of {@link TransactionHeaderType2 }
     * 
     */
    public TransactionHeaderType2 createTransactionHeaderType2() {
        return new TransactionHeaderType2();
    }

    /**
     * Create an instance of {@link GetPersonDataResponse }
     * 
     */
    public GetPersonDataResponse createGetPersonDataResponse() {
        return new GetPersonDataResponse();
    }

    /**
     * Create an instance of {@link PersonInformationType }
     * 
     */
    public PersonInformationType createPersonInformationType() {
        return new PersonInformationType();
    }

    /**
     * Create an instance of {@link SetPersonDataRequest }
     * 
     */
    public SetPersonDataRequest createSetPersonDataRequest() {
        return new SetPersonDataRequest();
    }

    /**
     * Create an instance of {@link SetPersonDataResponse }
     * 
     */
    public SetPersonDataResponse createSetPersonDataResponse() {
        return new SetPersonDataResponse();
    }

    /**
     * Create an instance of {@link CreateIdmIdentityRequest }
     * 
     */
    public CreateIdmIdentityRequest createCreateIdmIdentityRequest() {
        return new CreateIdmIdentityRequest();
    }

    /**
     * Create an instance of {@link IdentityOwnerType }
     * 
     */
    public IdentityOwnerType createIdentityOwnerType() {
        return new IdentityOwnerType();
    }

    /**
     * Create an instance of {@link CreateIdmIdentityResponse }
     * 
     */
    public CreateIdmIdentityResponse createCreateIdmIdentityResponse() {
        return new CreateIdmIdentityResponse();
    }

    /**
     * Create an instance of {@link SearchIdmIdentityRequest }
     * 
     */
    public SearchIdmIdentityRequest createSearchIdmIdentityRequest() {
        return new SearchIdmIdentityRequest();
    }

    /**
     * Create an instance of {@link SearchIdmIdentityResponse }
     * 
     */
    public SearchIdmIdentityResponse createSearchIdmIdentityResponse() {
        return new SearchIdmIdentityResponse();
    }

    /**
     * Create an instance of {@link SearchIdmIdentityResponseFieldsType }
     * 
     */
    public SearchIdmIdentityResponseFieldsType createSearchIdmIdentityResponseFieldsType() {
        return new SearchIdmIdentityResponseFieldsType();
    }

    /**
     * Create an instance of {@link BindExternalPivCardRequest }
     * 
     */
    public BindExternalPivCardRequest createBindExternalPivCardRequest() {
        return new BindExternalPivCardRequest();
    }

    /**
     * Create an instance of {@link PivModelCardCapabilityType }
     * 
     */
    public PivModelCardCapabilityType createPivModelCardCapabilityType() {
        return new PivModelCardCapabilityType();
    }

    /**
     * Create an instance of {@link PivModelCardHolderUniqueIdType }
     * 
     */
    public PivModelCardHolderUniqueIdType createPivModelCardHolderUniqueIdType() {
        return new PivModelCardHolderUniqueIdType();
    }

    /**
     * Create an instance of {@link PivModelCardPrintedInformationType }
     * 
     */
    public PivModelCardPrintedInformationType createPivModelCardPrintedInformationType() {
        return new PivModelCardPrintedInformationType();
    }

    /**
     * Create an instance of {@link BindExternalPivCardResponse }
     * 
     */
    public BindExternalPivCardResponse createBindExternalPivCardResponse() {
        return new BindExternalPivCardResponse();
    }

    /**
     * Create an instance of {@link CheckPivCardCertsRequest }
     * 
     */
    public CheckPivCardCertsRequest createCheckPivCardCertsRequest() {
        return new CheckPivCardCertsRequest();
    }

    /**
     * Create an instance of {@link CheckPivCardCertsResponse }
     * 
     */
    public CheckPivCardCertsResponse createCheckPivCardCertsResponse() {
        return new CheckPivCardCertsResponse();
    }

    /**
     * Create an instance of {@link GetFederalOrgInfoRequest }
     * 
     */
    public GetFederalOrgInfoRequest createGetFederalOrgInfoRequest() {
        return new GetFederalOrgInfoRequest();
    }

    /**
     * Create an instance of {@link GetFederalOrgInfoResponse }
     * 
     */
    public GetFederalOrgInfoResponse createGetFederalOrgInfoResponse() {
        return new GetFederalOrgInfoResponse();
    }

    /**
     * Create an instance of {@link FederalOrgInfoType }
     * 
     */
    public FederalOrgInfoType createFederalOrgInfoType() {
        return new FederalOrgInfoType();
    }

    /**
     * Create an instance of {@link ExtractImageAsJpegRequest }
     * 
     */
    public ExtractImageAsJpegRequest createExtractImageAsJpegRequest() {
        return new ExtractImageAsJpegRequest();
    }

    /**
     * Create an instance of {@link ExtractImageAsJpegResponse }
     * 
     */
    public ExtractImageAsJpegResponse createExtractImageAsJpegResponse() {
        return new ExtractImageAsJpegResponse();
    }

    /**
     * Create an instance of {@link PrepareBindExternalCardRequest }
     * 
     */
    public PrepareBindExternalCardRequest createPrepareBindExternalCardRequest() {
        return new PrepareBindExternalCardRequest();
    }

    /**
     * Create an instance of {@link PrepareBindExternalCardResponse }
     * 
     */
    public PrepareBindExternalCardResponse createPrepareBindExternalCardResponse() {
        return new PrepareBindExternalCardResponse();
    }

    /**
     * Create an instance of {@link CardExtractedInformationType }
     * 
     */
    public CardExtractedInformationType createCardExtractedInformationType() {
        return new CardExtractedInformationType();
    }

    /**
     * Create an instance of {@link CardCertificateInfoType }
     * 
     */
    public CardCertificateInfoType createCardCertificateInfoType() {
        return new CardCertificateInfoType();
    }

    /**
     * Create an instance of {@link ProcessingNotificationType }
     * 
     */
    public ProcessingNotificationType createProcessingNotificationType() {
        return new ProcessingNotificationType();
    }

    /**
     * Create an instance of {@link CommitBindExternalCardRequest }
     * 
     */
    public CommitBindExternalCardRequest createCommitBindExternalCardRequest() {
        return new CommitBindExternalCardRequest();
    }

    /**
     * Create an instance of {@link CommitBindExternalCardResponse }
     * 
     */
    public CommitBindExternalCardResponse createCommitBindExternalCardResponse() {
        return new CommitBindExternalCardResponse();
    }

    /**
     * Create an instance of {@link TypedValueType }
     * 
     */
    public TypedValueType createTypedValueType() {
        return new TypedValueType();
    }

    /**
     * Create an instance of {@link TaggedDataType }
     * 
     */
    public TaggedDataType createTaggedDataType() {
        return new TaggedDataType();
    }

    /**
     * Create an instance of {@link IdmPersonInfoType.IdentityInfo.PlaceOfBirthType }
     * 
     */
    public IdmPersonInfoType.IdentityInfo.PlaceOfBirthType createIdmPersonInfoTypeIdentityInfoPlaceOfBirthType() {
        return new IdmPersonInfoType.IdentityInfo.PlaceOfBirthType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameSalutationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "Salutation", scope = PersonInformationType.class)
    public JAXBElement<NameSalutationType> createPersonInformationTypeSalutation(NameSalutationType value) {
        return new JAXBElement<NameSalutationType>(_PersonInformationTypeSalutation_QNAME, NameSalutationType.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "MiddleName", scope = PersonInformationType.class)
    public JAXBElement<String> createPersonInformationTypeMiddleName(String value) {
        return new JAXBElement<String>(_PersonInformationTypeMiddleName_QNAME, String.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "NameSuffix", scope = PersonInformationType.class)
    public JAXBElement<String> createPersonInformationTypeNameSuffix(String value) {
        return new JAXBElement<String>(_PersonInformationTypeNameSuffix_QNAME, String.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "WorkAddress1", scope = PersonInformationType.class)
    public JAXBElement<String> createPersonInformationTypeWorkAddress1(String value) {
        return new JAXBElement<String>(_PersonInformationTypeWorkAddress1_QNAME, String.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "WorkAddress2", scope = PersonInformationType.class)
    public JAXBElement<String> createPersonInformationTypeWorkAddress2(String value) {
        return new JAXBElement<String>(_PersonInformationTypeWorkAddress2_QNAME, String.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "WorkAddress3", scope = PersonInformationType.class)
    public JAXBElement<String> createPersonInformationTypeWorkAddress3(String value) {
        return new JAXBElement<String>(_PersonInformationTypeWorkAddress3_QNAME, String.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "WorkCity", scope = PersonInformationType.class)
    public JAXBElement<String> createPersonInformationTypeWorkCity(String value) {
        return new JAXBElement<String>(_PersonInformationTypeWorkCity_QNAME, String.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "WorkState", scope = PersonInformationType.class)
    public JAXBElement<String> createPersonInformationTypeWorkState(String value) {
        return new JAXBElement<String>(_PersonInformationTypeWorkState_QNAME, String.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "WorkPostalCode", scope = PersonInformationType.class)
    public JAXBElement<String> createPersonInformationTypeWorkPostalCode(String value) {
        return new JAXBElement<String>(_PersonInformationTypeWorkPostalCode_QNAME, String.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "WorkCountry", scope = PersonInformationType.class)
    public JAXBElement<String> createPersonInformationTypeWorkCountry(String value) {
        return new JAXBElement<String>(_PersonInformationTypeWorkCountry_QNAME, String.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "WorkPhone", scope = PersonInformationType.class)
    public JAXBElement<String> createPersonInformationTypeWorkPhone(String value) {
        return new JAXBElement<String>(_PersonInformationTypeWorkPhone_QNAME, String.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "AlternatePhone", scope = PersonInformationType.class)
    public JAXBElement<String> createPersonInformationTypeAlternatePhone(String value) {
        return new JAXBElement<String>(_PersonInformationTypeAlternatePhone_QNAME, String.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "PrintDataFormat", scope = PacsFingerPrintInfoType.class)
    public JAXBElement<String> createPacsFingerPrintInfoTypePrintDataFormat(String value) {
        return new JAXBElement<String>(_PacsFingerPrintInfoTypePrintDataFormat_QNAME, String.class, PacsFingerPrintInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "PrintData", scope = PacsFingerPrintInfoType.class)
    public JAXBElement<byte[]> createPacsFingerPrintInfoTypePrintData(byte[] value) {
        return new JAXBElement<byte[]>(_PacsFingerPrintInfoTypePrintData_QNAME, byte[].class, PacsFingerPrintInfoType.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "ImageData", scope = PacsFacialImageInfoType.class)
    public JAXBElement<byte[]> createPacsFacialImageInfoTypeImageData(byte[] value) {
        return new JAXBElement<byte[]>(_PacsFacialImageInfoTypeImageData_QNAME, byte[].class, PacsFacialImageInfoType.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "ThumbNailData", scope = PacsFacialImageInfoType.class)
    public JAXBElement<byte[]> createPacsFacialImageInfoTypeThumbNailData(byte[] value) {
        return new JAXBElement<byte[]>(_PacsFacialImageInfoTypeThumbNailData_QNAME, byte[].class, PacsFacialImageInfoType.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FASCNDataFieldsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "FASCN", scope = PacsCardIdentifiersType.class)
    public JAXBElement<FASCNDataFieldsType> createPacsCardIdentifiersTypeFASCN(FASCNDataFieldsType value) {
        return new JAXBElement<FASCNDataFieldsType>(_PacsCardIdentifiersTypeFASCN_QNAME, FASCNDataFieldsType.class, PacsCardIdentifiersType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "PacsCardIdentifier", scope = PacsCardIdentifiersType.class)
    public JAXBElement<String> createPacsCardIdentifiersTypePacsCardIdentifier(String value) {
        return new JAXBElement<String>(_PacsCardIdentifiersTypePacsCardIdentifier_QNAME, String.class, PacsCardIdentifiersType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PacsCardIdentifiersType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "CardId", scope = PacsCardInformationType.class)
    public JAXBElement<PacsCardIdentifiersType> createPacsCardInformationTypeCardId(PacsCardIdentifiersType value) {
        return new JAXBElement<PacsCardIdentifiersType>(_PacsCardInformationTypeCardId_QNAME, PacsCardIdentifiersType.class, PacsCardInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PacsFacialImageInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "FacialImage", scope = PacsCardInformationType.class)
    public JAXBElement<PacsFacialImageInfoType> createPacsCardInformationTypeFacialImage(PacsFacialImageInfoType value) {
        return new JAXBElement<PacsFacialImageInfoType>(_PacsCardInformationTypeFacialImage_QNAME, PacsFacialImageInfoType.class, PacsCardInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PacsFingerPrintInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "FingerPrints", scope = PacsCardInformationType.class)
    public JAXBElement<PacsFingerPrintInfoType> createPacsCardInformationTypeFingerPrints(PacsFingerPrintInfoType value) {
        return new JAXBElement<PacsFingerPrintInfoType>(_PacsCardInformationTypeFingerPrints_QNAME, PacsFingerPrintInfoType.class, PacsCardInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamePrefixType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "Prefix", scope = PacsPersonInfoDataType.class)
    public JAXBElement<NamePrefixType> createPacsPersonInfoDataTypePrefix(NamePrefixType value) {
        return new JAXBElement<NamePrefixType>(_PacsPersonInfoDataTypePrefix_QNAME, NamePrefixType.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "FirstName", scope = PacsPersonInfoDataType.class)
    public JAXBElement<String> createPacsPersonInfoDataTypeFirstName(String value) {
        return new JAXBElement<String>(_PacsPersonInfoDataTypeFirstName_QNAME, String.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "MiddleName", scope = PacsPersonInfoDataType.class)
    public JAXBElement<String> createPacsPersonInfoDataTypeMiddleName(String value) {
        return new JAXBElement<String>(_PacsPersonInfoDataTypeMiddleName_QNAME, String.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "LastName", scope = PacsPersonInfoDataType.class)
    public JAXBElement<String> createPacsPersonInfoDataTypeLastName(String value) {
        return new JAXBElement<String>(_PacsPersonInfoDataTypeLastName_QNAME, String.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameGenerationQualifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "GenerationQualifier", scope = PacsPersonInfoDataType.class)
    public JAXBElement<NameGenerationQualifierType> createPacsPersonInfoDataTypeGenerationQualifier(NameGenerationQualifierType value) {
        return new JAXBElement<NameGenerationQualifierType>(_PacsPersonInfoDataTypeGenerationQualifier_QNAME, NameGenerationQualifierType.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "NameSuffix", scope = PacsPersonInfoDataType.class)
    public JAXBElement<String> createPacsPersonInfoDataTypeNameSuffix(String value) {
        return new JAXBElement<String>(_PacsPersonInfoDataTypeNameSuffix_QNAME, String.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "DOB", scope = PacsPersonInfoDataType.class)
    public JAXBElement<XMLGregorianCalendar> createPacsPersonInfoDataTypeDOB(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_PacsPersonInfoDataTypeDOB_QNAME, XMLGregorianCalendar.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "CityOfBirth", scope = PacsPersonInfoDataType.class)
    public JAXBElement<String> createPacsPersonInfoDataTypeCityOfBirth(String value) {
        return new JAXBElement<String>(_PacsPersonInfoDataTypeCityOfBirth_QNAME, String.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StateCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "StateOfBirth", scope = PacsPersonInfoDataType.class)
    public JAXBElement<StateCodeType> createPacsPersonInfoDataTypeStateOfBirth(StateCodeType value) {
        return new JAXBElement<StateCodeType>(_PacsPersonInfoDataTypeStateOfBirth_QNAME, StateCodeType.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CountryCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "CountryOfBirth", scope = PacsPersonInfoDataType.class)
    public JAXBElement<CountryCodeType> createPacsPersonInfoDataTypeCountryOfBirth(CountryCodeType value) {
        return new JAXBElement<CountryCodeType>(_PacsPersonInfoDataTypeCountryOfBirth_QNAME, CountryCodeType.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CountryCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "CountryOfCitizenship", scope = PacsPersonInfoDataType.class)
    public JAXBElement<CountryCodeType> createPacsPersonInfoDataTypeCountryOfCitizenship(CountryCodeType value) {
        return new JAXBElement<CountryCodeType>(_PacsPersonInfoDataTypeCountryOfCitizenship_QNAME, CountryCodeType.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "VisaNumber", scope = PacsPersonInfoDataType.class)
    public JAXBElement<String> createPacsPersonInfoDataTypeVisaNumber(String value) {
        return new JAXBElement<String>(_PacsPersonInfoDataTypeVisaNumber_QNAME, String.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "ARN", scope = PacsPersonInfoDataType.class)
    public JAXBElement<String> createPacsPersonInfoDataTypeARN(String value) {
        return new JAXBElement<String>(_PacsPersonInfoDataTypeARN_QNAME, String.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ForeignNationalIdInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "ForeignID", scope = PacsPersonInfoDataType.class)
    public JAXBElement<ForeignNationalIdInfoType> createPacsPersonInfoDataTypeForeignID(ForeignNationalIdInfoType value) {
        return new JAXBElement<ForeignNationalIdInfoType>(_PacsPersonInfoDataTypeForeignID_QNAME, ForeignNationalIdInfoType.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "PositionTitle", scope = PacsPersonInfoDataType.class)
    public JAXBElement<String> createPacsPersonInfoDataTypePositionTitle(String value) {
        return new JAXBElement<String>(_PacsPersonInfoDataTypePositionTitle_QNAME, String.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "PositionSensitivity", scope = PacsPersonInfoDataType.class)
    public JAXBElement<Integer> createPacsPersonInfoDataTypePositionSensitivity(Integer value) {
        return new JAXBElement<Integer>(_PacsPersonInfoDataTypePositionSensitivity_QNAME, Integer.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link YesNoCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "EmergencyResponder", scope = PacsPersonInfoDataType.class)
    public JAXBElement<YesNoCodeType> createPacsPersonInfoDataTypeEmergencyResponder(YesNoCodeType value) {
        return new JAXBElement<YesNoCodeType>(_PacsPersonInfoDataTypeEmergencyResponder_QNAME, YesNoCodeType.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CredentialCategoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "CredentialCategory", scope = PacsPersonInfoDataType.class)
    public JAXBElement<CredentialCategoryType> createPacsPersonInfoDataTypeCredentialCategory(CredentialCategoryType value) {
        return new JAXBElement<CredentialCategoryType>(_PacsPersonInfoDataTypeCredentialCategory_QNAME, CredentialCategoryType.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganizationCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "Organization", scope = PacsPersonInfoDataType.class)
    public JAXBElement<OrganizationCodeType> createPacsPersonInfoDataTypeOrganization(OrganizationCodeType value) {
        return new JAXBElement<OrganizationCodeType>(_PacsPersonInfoDataTypeOrganization_QNAME, OrganizationCodeType.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpdivCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "OPDIV", scope = PacsPersonInfoDataType.class)
    public JAXBElement<OpdivCodeType> createPacsPersonInfoDataTypeOPDIV(OpdivCodeType value) {
        return new JAXBElement<OpdivCodeType>(_PacsPersonInfoDataTypeOPDIV_QNAME, OpdivCodeType.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "AffiliationCode", scope = PacsPersonInfoDataType.class)
    public JAXBElement<String> createPacsPersonInfoDataTypeAffiliationCode(String value) {
        return new JAXBElement<String>(_PacsPersonInfoDataTypeAffiliationCode_QNAME, String.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "EmployerName", scope = PacsPersonInfoDataType.class)
    public JAXBElement<String> createPacsPersonInfoDataTypeEmployerName(String value) {
        return new JAXBElement<String>(_PacsPersonInfoDataTypeEmployerName_QNAME, String.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "WorkLocationCode", scope = PacsPersonInfoDataType.class)
    public JAXBElement<String> createPacsPersonInfoDataTypeWorkLocationCode(String value) {
        return new JAXBElement<String>(_PacsPersonInfoDataTypeWorkLocationCode_QNAME, String.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "WorkPhone", scope = PacsPersonInfoDataType.class)
    public JAXBElement<String> createPacsPersonInfoDataTypeWorkPhone(String value) {
        return new JAXBElement<String>(_PacsPersonInfoDataTypeWorkPhone_QNAME, String.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "WorkPhoneExtension", scope = PacsPersonInfoDataType.class)
    public JAXBElement<String> createPacsPersonInfoDataTypeWorkPhoneExtension(String value) {
        return new JAXBElement<String>(_PacsPersonInfoDataTypeWorkPhoneExtension_QNAME, String.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "CostCenter", scope = PacsPersonInfoDataType.class)
    public JAXBElement<String> createPacsPersonInfoDataTypeCostCenter(String value) {
        return new JAXBElement<String>(_PacsPersonInfoDataTypeCostCenter_QNAME, String.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "SubAgency", scope = PacsPersonInfoDataType.class)
    public JAXBElement<String> createPacsPersonInfoDataTypeSubAgency(String value) {
        return new JAXBElement<String>(_PacsPersonInfoDataTypeSubAgency_QNAME, String.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "PrimaryEmailAddress", scope = PacsPersonInfoDataType.class)
    public JAXBElement<String> createPacsPersonInfoDataTypePrimaryEmailAddress(String value) {
        return new JAXBElement<String>(_PacsPersonInfoDataTypePrimaryEmailAddress_QNAME, String.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "AlternateEmailAddress", scope = PacsPersonInfoDataType.class)
    public JAXBElement<String> createPacsPersonInfoDataTypeAlternateEmailAddress(String value) {
        return new JAXBElement<String>(_PacsPersonInfoDataTypeAlternateEmailAddress_QNAME, String.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "UPN", scope = PacsPersonInfoDataType.class)
    public JAXBElement<String> createPacsPersonInfoDataTypeUPN(String value) {
        return new JAXBElement<String>(_PacsPersonInfoDataTypeUPN_QNAME, String.class, PacsPersonInfoDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "HHSID", scope = PacsPersonIdentifiersType.class)
    public JAXBElement<String> createPacsPersonIdentifiersTypeHHSID(String value) {
        return new JAXBElement<String>(_PacsPersonIdentifiersTypeHHSID_QNAME, String.class, PacsPersonIdentifiersType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "EmployeeID", scope = PacsPersonIdentifiersType.class)
    public JAXBElement<String> createPacsPersonIdentifiersTypeEmployeeID(String value) {
        return new JAXBElement<String>(_PacsPersonIdentifiersTypeEmployeeID_QNAME, String.class, PacsPersonIdentifiersType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "MiddleName", scope = InductionDataType.class)
    public JAXBElement<String> createInductionDataTypeMiddleName(String value) {
        return new JAXBElement<String>(_PacsPersonInfoDataTypeMiddleName_QNAME, String.class, InductionDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "EmployeeID", scope = InductionDataType.class)
    public JAXBElement<String> createInductionDataTypeEmployeeID(String value) {
        return new JAXBElement<String>(_PacsPersonIdentifiersTypeEmployeeID_QNAME, String.class, InductionDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "CopsAgency", scope = InductionDataType.class)
    public JAXBElement<String> createInductionDataTypeCopsAgency(String value) {
        return new JAXBElement<String>(_InductionDataTypeCopsAgency_QNAME, String.class, InductionDataType.class, value);
    }

}
