//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         		This element contains data items which may be used to
 *         		uniquely identify a person on the PACS and in the IDMS.  
 *         		At least one of the sub elements must be specified when 
 *         		attempting to get or set a persons data on the PACS. 
 *         	
 * 
 * <p>Java class for PacsPersonIdentifiersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PacsPersonIdentifiersType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="HHSID" type="{http://hspd12.hhs.gov/federated/enrollment/v1}PersonIdType" minOccurs="0"/&gt;
 *         &lt;element name="EmployeeID" type="{http://hspd12.hhs.gov/federated/enrollment/v1}OpdivEmployeeIDType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PacsPersonIdentifiersType", propOrder = {
    "hhsid",
    "employeeID"
})
public class PacsPersonIdentifiersType {

    @XmlElementRef(name = "HHSID", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> hhsid;
    @XmlElementRef(name = "EmployeeID", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> employeeID;

    /**
     * Gets the value of the hhsid property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getHHSID() {
        return hhsid;
    }

    /**
     * Sets the value of the hhsid property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setHHSID(JAXBElement<String> value) {
        this.hhsid = value;
    }

    /**
     * Gets the value of the employeeID property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getEmployeeID() {
        return employeeID;
    }

    /**
     * Sets the value of the employeeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setEmployeeID(JAXBElement<String> value) {
        this.employeeID = value;
    }

}
