//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         		This element describes the final result of a PACS pending operation 
 *         		that has completed. 
 *         	
 * 
 * <p>Java class for PacsPendingOperationResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PacsPendingOperationResultType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="UpdatePersonInfo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="AddCard" type="{http://hspd12.hhs.gov/federated/enrollment/v1}PacsCardIdentifiersType"/&gt;
 *           &lt;element name="UpdateCard" type="{http://hspd12.hhs.gov/federated/enrollment/v1}PacsCardIdentifiersType"/&gt;
 *           &lt;element name="SuspendCard" type="{http://hspd12.hhs.gov/federated/enrollment/v1}PacsCardIdentifiersType"/&gt;
 *           &lt;element name="ReactivateCard" type="{http://hspd12.hhs.gov/federated/enrollment/v1}PacsCardIdentifiersType"/&gt;
 *           &lt;element name="RevokeCard" type="{http://hspd12.hhs.gov/federated/enrollment/v1}PacsCardIdentifiersType"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="ResultCode"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Success"/&gt;
 *               &lt;enumeration value="NotFound"/&gt;
 *               &lt;enumeration value="Reject-InvalidData"/&gt;
 *               &lt;enumeration value="Reject-InvalidDataForPACS"/&gt;
 *               &lt;enumeration value="Reject-Duplicate"/&gt;
 *               &lt;enumeration value="Reject-NotSettable"/&gt;
 *               &lt;enumeration value="Reject-MissingData"/&gt;
 *               &lt;enumeration value="Failed"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FailureDetailMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PacsPendingOperationResultType", propOrder = {
    "updatePersonInfo",
    "addCard",
    "updateCard",
    "suspendCard",
    "reactivateCard",
    "revokeCard",
    "resultCode",
    "failureDetailMessage"
})
public class PacsPendingOperationResultType {

    @XmlElement(name = "UpdatePersonInfo")
    protected String updatePersonInfo;
    @XmlElement(name = "AddCard")
    protected PacsCardIdentifiersType addCard;
    @XmlElement(name = "UpdateCard")
    protected PacsCardIdentifiersType updateCard;
    @XmlElement(name = "SuspendCard")
    protected PacsCardIdentifiersType suspendCard;
    @XmlElement(name = "ReactivateCard")
    protected PacsCardIdentifiersType reactivateCard;
    @XmlElement(name = "RevokeCard")
    protected PacsCardIdentifiersType revokeCard;
    @XmlElement(name = "ResultCode", required = true)
    protected String resultCode;
    @XmlElement(name = "FailureDetailMessage")
    protected String failureDetailMessage;

    /**
     * Gets the value of the updatePersonInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdatePersonInfo() {
        return updatePersonInfo;
    }

    /**
     * Sets the value of the updatePersonInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatePersonInfo(String value) {
        this.updatePersonInfo = value;
    }

    /**
     * Gets the value of the addCard property.
     * 
     * @return
     *     possible object is
     *     {@link PacsCardIdentifiersType }
     *     
     */
    public PacsCardIdentifiersType getAddCard() {
        return addCard;
    }

    /**
     * Sets the value of the addCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link PacsCardIdentifiersType }
     *     
     */
    public void setAddCard(PacsCardIdentifiersType value) {
        this.addCard = value;
    }

    /**
     * Gets the value of the updateCard property.
     * 
     * @return
     *     possible object is
     *     {@link PacsCardIdentifiersType }
     *     
     */
    public PacsCardIdentifiersType getUpdateCard() {
        return updateCard;
    }

    /**
     * Sets the value of the updateCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link PacsCardIdentifiersType }
     *     
     */
    public void setUpdateCard(PacsCardIdentifiersType value) {
        this.updateCard = value;
    }

    /**
     * Gets the value of the suspendCard property.
     * 
     * @return
     *     possible object is
     *     {@link PacsCardIdentifiersType }
     *     
     */
    public PacsCardIdentifiersType getSuspendCard() {
        return suspendCard;
    }

    /**
     * Sets the value of the suspendCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link PacsCardIdentifiersType }
     *     
     */
    public void setSuspendCard(PacsCardIdentifiersType value) {
        this.suspendCard = value;
    }

    /**
     * Gets the value of the reactivateCard property.
     * 
     * @return
     *     possible object is
     *     {@link PacsCardIdentifiersType }
     *     
     */
    public PacsCardIdentifiersType getReactivateCard() {
        return reactivateCard;
    }

    /**
     * Sets the value of the reactivateCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link PacsCardIdentifiersType }
     *     
     */
    public void setReactivateCard(PacsCardIdentifiersType value) {
        this.reactivateCard = value;
    }

    /**
     * Gets the value of the revokeCard property.
     * 
     * @return
     *     possible object is
     *     {@link PacsCardIdentifiersType }
     *     
     */
    public PacsCardIdentifiersType getRevokeCard() {
        return revokeCard;
    }

    /**
     * Sets the value of the revokeCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link PacsCardIdentifiersType }
     *     
     */
    public void setRevokeCard(PacsCardIdentifiersType value) {
        this.revokeCard = value;
    }

    /**
     * Gets the value of the resultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * Sets the value of the resultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultCode(String value) {
        this.resultCode = value;
    }

    /**
     * Gets the value of the failureDetailMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFailureDetailMessage() {
        return failureDetailMessage;
    }

    /**
     * Sets the value of the failureDetailMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFailureDetailMessage(String value) {
        this.failureDetailMessage = value;
    }

}
