//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         		This element contains data items which may be used to
 *         		uniquely identify a card belonging to a person on the PACS.  
 *         		At least one of the sub elements must be specified when 
 *         		attempting to get or set information relating to a persons card. 
 *         	
 * 
 * <p>Java class for PacsCardIdentifiersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PacsCardIdentifiersType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FASCN" type="{http://hspd12.hhs.gov/federated/enrollment/v1}FASCNDataFieldsType" minOccurs="0"/&gt;
 *         &lt;element name="PacsCardIdentifier" type="{http://hspd12.hhs.gov/federated/enrollment/v1}PacsCardIdStringType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PacsCardIdentifiersType", propOrder = {
    "fascn",
    "pacsCardIdentifier"
})
public class PacsCardIdentifiersType {

    @XmlElementRef(name = "FASCN", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<FASCNDataFieldsType> fascn;
    @XmlElementRef(name = "PacsCardIdentifier", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> pacsCardIdentifier;

    /**
     * Gets the value of the fascn property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link FASCNDataFieldsType }{@code >}
     *     
     */
    public JAXBElement<FASCNDataFieldsType> getFASCN() {
        return fascn;
    }

    /**
     * Sets the value of the fascn property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link FASCNDataFieldsType }{@code >}
     *     
     */
    public void setFASCN(JAXBElement<FASCNDataFieldsType> value) {
        this.fascn = value;
    }

    /**
     * Gets the value of the pacsCardIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPacsCardIdentifier() {
        return pacsCardIdentifier;
    }

    /**
     * Sets the value of the pacsCardIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPacsCardIdentifier(JAXBElement<String> value) {
        this.pacsCardIdentifier = value;
    }

}
