//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 *         		This Type defines the data items associated with a
 *         		Person on the PACS system.
 *         	
 * 
 * <p>Java class for PacsPersonInfoDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PacsPersonInfoDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Prefix" type="{http://hspd12.hhs.gov/federated/enrollment/v1}NamePrefixType" minOccurs="0"/&gt;
 *         &lt;element name="FirstName" type="{http://hspd12.hhs.gov/federated/enrollment/v1}FirstNameType" minOccurs="0"/&gt;
 *         &lt;element name="MiddleName" type="{http://hspd12.hhs.gov/federated/enrollment/v1}MiddleNameType" minOccurs="0"/&gt;
 *         &lt;element name="LastName" type="{http://hspd12.hhs.gov/federated/enrollment/v1}LastNameType" minOccurs="0"/&gt;
 *         &lt;element name="GenerationQualifier" type="{http://hspd12.hhs.gov/federated/enrollment/v1}NameGenerationQualifierType" minOccurs="0"/&gt;
 *         &lt;element name="NameSuffix" type="{http://hspd12.hhs.gov/federated/enrollment/v1}NameSuffixType" minOccurs="0"/&gt;
 *         &lt;element name="DOB" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="CityOfBirth" type="{http://hspd12.hhs.gov/federated/enrollment/v1}CityOfBirthType" minOccurs="0"/&gt;
 *         &lt;element name="StateOfBirth" type="{http://hspd12.hhs.gov/federated/enrollment/v1}StateCodeType" minOccurs="0"/&gt;
 *         &lt;element name="CountryOfBirth" type="{http://hspd12.hhs.gov/federated/enrollment/v1}CountryCodeType" minOccurs="0"/&gt;
 *         &lt;element name="CountryOfCitizenship" type="{http://hspd12.hhs.gov/federated/enrollment/v1}CountryCodeType" minOccurs="0"/&gt;
 *         &lt;element name="VisaNumber" type="{http://hspd12.hhs.gov/federated/enrollment/v1}VisaNumberType" minOccurs="0"/&gt;
 *         &lt;element name="ARN" type="{http://hspd12.hhs.gov/federated/enrollment/v1}AlienRegistrationNumberType" minOccurs="0"/&gt;
 *         &lt;element name="ForeignID" type="{http://hspd12.hhs.gov/federated/enrollment/v1}ForeignNationalIdInfoType" minOccurs="0"/&gt;
 *         &lt;element name="PositionTitle" type="{http://hspd12.hhs.gov/federated/enrollment/v1}PositionTitleType" minOccurs="0"/&gt;
 *         &lt;element name="PositionSensitivity" type="{http://hspd12.hhs.gov/federated/enrollment/v1}PositionSensitivityType" minOccurs="0"/&gt;
 *         &lt;element name="EmergencyResponder" type="{http://hspd12.hhs.gov/federated/enrollment/v1}YesNoCodeType" minOccurs="0"/&gt;
 *         &lt;element name="CredentialCategory" type="{http://hspd12.hhs.gov/federated/enrollment/v1}CredentialCategoryType" minOccurs="0"/&gt;
 *         &lt;element name="Organization" type="{http://hspd12.hhs.gov/federated/enrollment/v1}OrganizationCodeType" minOccurs="0"/&gt;
 *         &lt;element name="OPDIV" type="{http://hspd12.hhs.gov/federated/enrollment/v1}OpdivCodeType" minOccurs="0"/&gt;
 *         &lt;element name="AffiliationCode" type="{http://hspd12.hhs.gov/federated/enrollment/v1}AffiliationCodeType" minOccurs="0"/&gt;
 *         &lt;element name="EmployerName" type="{http://hspd12.hhs.gov/federated/enrollment/v1}EmployerNameType" minOccurs="0"/&gt;
 *         &lt;element name="WorkLocationCode" type="{http://hspd12.hhs.gov/federated/enrollment/v1}WorkLocationCodeType" minOccurs="0"/&gt;
 *         &lt;element name="WorkPhone" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="30"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="WorkPhoneExtension" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="8"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CostCenter" type="{http://hspd12.hhs.gov/federated/enrollment/v1}CostCenterType" minOccurs="0"/&gt;
 *         &lt;element name="SubAgency" type="{http://hspd12.hhs.gov/federated/enrollment/v1}SubAgencyType" minOccurs="0"/&gt;
 *         &lt;element name="PrimaryEmailAddress" type="{http://hspd12.hhs.gov/federated/enrollment/v1}EmailAddressType" minOccurs="0"/&gt;
 *         &lt;element name="AlternateEmailAddress" type="{http://hspd12.hhs.gov/federated/enrollment/v1}EmailAddressType" minOccurs="0"/&gt;
 *         &lt;element name="UPN" type="{http://hspd12.hhs.gov/federated/enrollment/v1}UPNType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PacsPersonInfoDataType", propOrder = {
    "prefix",
    "firstName",
    "middleName",
    "lastName",
    "generationQualifier",
    "nameSuffix",
    "dob",
    "cityOfBirth",
    "stateOfBirth",
    "countryOfBirth",
    "countryOfCitizenship",
    "visaNumber",
    "arn",
    "foreignID",
    "positionTitle",
    "positionSensitivity",
    "emergencyResponder",
    "credentialCategory",
    "organization",
    "opdiv",
    "affiliationCode",
    "employerName",
    "workLocationCode",
    "workPhone",
    "workPhoneExtension",
    "costCenter",
    "subAgency",
    "primaryEmailAddress",
    "alternateEmailAddress",
    "upn"
})
public class PacsPersonInfoDataType {

    @XmlElementRef(name = "Prefix", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<NamePrefixType> prefix;
    @XmlElementRef(name = "FirstName", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> firstName;
    @XmlElementRef(name = "MiddleName", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> middleName;
    @XmlElementRef(name = "LastName", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lastName;
    @XmlElementRef(name = "GenerationQualifier", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<NameGenerationQualifierType> generationQualifier;
    @XmlElementRef(name = "NameSuffix", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> nameSuffix;
    @XmlElementRef(name = "DOB", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> dob;
    @XmlElementRef(name = "CityOfBirth", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> cityOfBirth;
    @XmlElementRef(name = "StateOfBirth", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<StateCodeType> stateOfBirth;
    @XmlElementRef(name = "CountryOfBirth", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<CountryCodeType> countryOfBirth;
    @XmlElementRef(name = "CountryOfCitizenship", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<CountryCodeType> countryOfCitizenship;
    @XmlElementRef(name = "VisaNumber", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> visaNumber;
    @XmlElementRef(name = "ARN", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> arn;
    @XmlElementRef(name = "ForeignID", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<ForeignNationalIdInfoType> foreignID;
    @XmlElementRef(name = "PositionTitle", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> positionTitle;
    @XmlElementRef(name = "PositionSensitivity", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> positionSensitivity;
    @XmlElementRef(name = "EmergencyResponder", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<YesNoCodeType> emergencyResponder;
    @XmlElementRef(name = "CredentialCategory", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<CredentialCategoryType> credentialCategory;
    @XmlElementRef(name = "Organization", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<OrganizationCodeType> organization;
    @XmlElementRef(name = "OPDIV", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<OpdivCodeType> opdiv;
    @XmlElementRef(name = "AffiliationCode", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> affiliationCode;
    @XmlElementRef(name = "EmployerName", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> employerName;
    @XmlElementRef(name = "WorkLocationCode", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> workLocationCode;
    @XmlElementRef(name = "WorkPhone", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> workPhone;
    @XmlElementRef(name = "WorkPhoneExtension", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> workPhoneExtension;
    @XmlElementRef(name = "CostCenter", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> costCenter;
    @XmlElementRef(name = "SubAgency", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> subAgency;
    @XmlElementRef(name = "PrimaryEmailAddress", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> primaryEmailAddress;
    @XmlElementRef(name = "AlternateEmailAddress", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> alternateEmailAddress;
    @XmlElementRef(name = "UPN", namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> upn;

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link NamePrefixType }{@code >}
     *     
     */
    public JAXBElement<NamePrefixType> getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link NamePrefixType }{@code >}
     *     
     */
    public void setPrefix(JAXBElement<NamePrefixType> value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFirstName(JAXBElement<String> value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMiddleName(JAXBElement<String> value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLastName(JAXBElement<String> value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the generationQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link NameGenerationQualifierType }{@code >}
     *     
     */
    public JAXBElement<NameGenerationQualifierType> getGenerationQualifier() {
        return generationQualifier;
    }

    /**
     * Sets the value of the generationQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link NameGenerationQualifierType }{@code >}
     *     
     */
    public void setGenerationQualifier(JAXBElement<NameGenerationQualifierType> value) {
        this.generationQualifier = value;
    }

    /**
     * Gets the value of the nameSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getNameSuffix() {
        return nameSuffix;
    }

    /**
     * Sets the value of the nameSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNameSuffix(JAXBElement<String> value) {
        this.nameSuffix = value;
    }

    /**
     * Gets the value of the dob property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getDOB() {
        return dob;
    }

    /**
     * Sets the value of the dob property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setDOB(JAXBElement<XMLGregorianCalendar> value) {
        this.dob = value;
    }

    /**
     * Gets the value of the cityOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCityOfBirth() {
        return cityOfBirth;
    }

    /**
     * Sets the value of the cityOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCityOfBirth(JAXBElement<String> value) {
        this.cityOfBirth = value;
    }

    /**
     * Gets the value of the stateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link StateCodeType }{@code >}
     *     
     */
    public JAXBElement<StateCodeType> getStateOfBirth() {
        return stateOfBirth;
    }

    /**
     * Sets the value of the stateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link StateCodeType }{@code >}
     *     
     */
    public void setStateOfBirth(JAXBElement<StateCodeType> value) {
        this.stateOfBirth = value;
    }

    /**
     * Gets the value of the countryOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CountryCodeType }{@code >}
     *     
     */
    public JAXBElement<CountryCodeType> getCountryOfBirth() {
        return countryOfBirth;
    }

    /**
     * Sets the value of the countryOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CountryCodeType }{@code >}
     *     
     */
    public void setCountryOfBirth(JAXBElement<CountryCodeType> value) {
        this.countryOfBirth = value;
    }

    /**
     * Gets the value of the countryOfCitizenship property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CountryCodeType }{@code >}
     *     
     */
    public JAXBElement<CountryCodeType> getCountryOfCitizenship() {
        return countryOfCitizenship;
    }

    /**
     * Sets the value of the countryOfCitizenship property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CountryCodeType }{@code >}
     *     
     */
    public void setCountryOfCitizenship(JAXBElement<CountryCodeType> value) {
        this.countryOfCitizenship = value;
    }

    /**
     * Gets the value of the visaNumber property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getVisaNumber() {
        return visaNumber;
    }

    /**
     * Sets the value of the visaNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setVisaNumber(JAXBElement<String> value) {
        this.visaNumber = value;
    }

    /**
     * Gets the value of the arn property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getARN() {
        return arn;
    }

    /**
     * Sets the value of the arn property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setARN(JAXBElement<String> value) {
        this.arn = value;
    }

    /**
     * Gets the value of the foreignID property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ForeignNationalIdInfoType }{@code >}
     *     
     */
    public JAXBElement<ForeignNationalIdInfoType> getForeignID() {
        return foreignID;
    }

    /**
     * Sets the value of the foreignID property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ForeignNationalIdInfoType }{@code >}
     *     
     */
    public void setForeignID(JAXBElement<ForeignNationalIdInfoType> value) {
        this.foreignID = value;
    }

    /**
     * Gets the value of the positionTitle property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPositionTitle() {
        return positionTitle;
    }

    /**
     * Sets the value of the positionTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPositionTitle(JAXBElement<String> value) {
        this.positionTitle = value;
    }

    /**
     * Gets the value of the positionSensitivity property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getPositionSensitivity() {
        return positionSensitivity;
    }

    /**
     * Sets the value of the positionSensitivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setPositionSensitivity(JAXBElement<Integer> value) {
        this.positionSensitivity = value;
    }

    /**
     * Gets the value of the emergencyResponder property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link YesNoCodeType }{@code >}
     *     
     */
    public JAXBElement<YesNoCodeType> getEmergencyResponder() {
        return emergencyResponder;
    }

    /**
     * Sets the value of the emergencyResponder property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link YesNoCodeType }{@code >}
     *     
     */
    public void setEmergencyResponder(JAXBElement<YesNoCodeType> value) {
        this.emergencyResponder = value;
    }

    /**
     * Gets the value of the credentialCategory property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CredentialCategoryType }{@code >}
     *     
     */
    public JAXBElement<CredentialCategoryType> getCredentialCategory() {
        return credentialCategory;
    }

    /**
     * Sets the value of the credentialCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CredentialCategoryType }{@code >}
     *     
     */
    public void setCredentialCategory(JAXBElement<CredentialCategoryType> value) {
        this.credentialCategory = value;
    }

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link OrganizationCodeType }{@code >}
     *     
     */
    public JAXBElement<OrganizationCodeType> getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link OrganizationCodeType }{@code >}
     *     
     */
    public void setOrganization(JAXBElement<OrganizationCodeType> value) {
        this.organization = value;
    }

    /**
     * Gets the value of the opdiv property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link OpdivCodeType }{@code >}
     *     
     */
    public JAXBElement<OpdivCodeType> getOPDIV() {
        return opdiv;
    }

    /**
     * Sets the value of the opdiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link OpdivCodeType }{@code >}
     *     
     */
    public void setOPDIV(JAXBElement<OpdivCodeType> value) {
        this.opdiv = value;
    }

    /**
     * Gets the value of the affiliationCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAffiliationCode() {
        return affiliationCode;
    }

    /**
     * Sets the value of the affiliationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAffiliationCode(JAXBElement<String> value) {
        this.affiliationCode = value;
    }

    /**
     * Gets the value of the employerName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getEmployerName() {
        return employerName;
    }

    /**
     * Sets the value of the employerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setEmployerName(JAXBElement<String> value) {
        this.employerName = value;
    }

    /**
     * Gets the value of the workLocationCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWorkLocationCode() {
        return workLocationCode;
    }

    /**
     * Sets the value of the workLocationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWorkLocationCode(JAXBElement<String> value) {
        this.workLocationCode = value;
    }

    /**
     * Gets the value of the workPhone property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWorkPhone() {
        return workPhone;
    }

    /**
     * Sets the value of the workPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWorkPhone(JAXBElement<String> value) {
        this.workPhone = value;
    }

    /**
     * Gets the value of the workPhoneExtension property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWorkPhoneExtension() {
        return workPhoneExtension;
    }

    /**
     * Sets the value of the workPhoneExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWorkPhoneExtension(JAXBElement<String> value) {
        this.workPhoneExtension = value;
    }

    /**
     * Gets the value of the costCenter property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCostCenter() {
        return costCenter;
    }

    /**
     * Sets the value of the costCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCostCenter(JAXBElement<String> value) {
        this.costCenter = value;
    }

    /**
     * Gets the value of the subAgency property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSubAgency() {
        return subAgency;
    }

    /**
     * Sets the value of the subAgency property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSubAgency(JAXBElement<String> value) {
        this.subAgency = value;
    }

    /**
     * Gets the value of the primaryEmailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPrimaryEmailAddress() {
        return primaryEmailAddress;
    }

    /**
     * Sets the value of the primaryEmailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPrimaryEmailAddress(JAXBElement<String> value) {
        this.primaryEmailAddress = value;
    }

    /**
     * Gets the value of the alternateEmailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAlternateEmailAddress() {
        return alternateEmailAddress;
    }

    /**
     * Sets the value of the alternateEmailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAlternateEmailAddress(JAXBElement<String> value) {
        this.alternateEmailAddress = value;
    }

    /**
     * Gets the value of the upn property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getUPN() {
        return upn;
    }

    /**
     * Sets the value of the upn property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setUPN(JAXBElement<String> value) {
        this.upn = value;
    }

}
