//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersonInvestigationCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PersonInvestigationCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="NONE"/&gt;
 *     &lt;enumeration value="SAC"/&gt;
 *     &lt;enumeration value="NAC"/&gt;
 *     &lt;enumeration value="NACI"/&gt;
 *     &lt;enumeration value="CNACI"/&gt;
 *     &lt;enumeration value="ANACI"/&gt;
 *     &lt;enumeration value="SSBI"/&gt;
 *     &lt;enumeration value="SSBI-PR"/&gt;
 *     &lt;enumeration value="NACIC"/&gt;
 *     &lt;enumeration value="NACLC"/&gt;
 *     &lt;enumeration value="BI"/&gt;
 *     &lt;enumeration value="MBI"/&gt;
 *     &lt;enumeration value="LBI"/&gt;
 *     &lt;enumeration value="TIER1"/&gt;
 *     &lt;enumeration value="TIER2"/&gt;
 *     &lt;enumeration value="TIER3"/&gt;
 *     &lt;enumeration value="TIER4"/&gt;
 *     &lt;enumeration value="TIER5"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PersonInvestigationCodeType")
@XmlEnum
public enum PersonInvestigationCodeType {


    /**
     * 
     * 						No background check
     * 		        	
     * 
     */
    NONE("NONE"),

    /**
     * 
     *                         Special Agreement Check
     *                     
     * 
     */
    SAC("SAC"),

    /**
     * 
     *                         National Agency Check
     *                     
     * 
     */
    NAC("NAC"),

    /**
     * 
     * 						name & fingerprint checks & written inquiries
     * 		        	
     * 
     */
    NACI("NACI"),

    /**
     * 
     * 						NACI plus extra checks for employees who work with children.
     * 		        	
     * 
     */
    CNACI("CNACI"),

    /**
     * 
     * 						Access NACI
     * 		        	
     * 
     */
    ANACI("ANACI"),

    /**
     * 
     * 						Single Scope Background Investigation
     * 		        	
     * 
     */
    SSBI("SSBI"),

    /**
     * 
     * 						Single Scope Background Investigation with Periodic Reinvestigation (SSBI-PR)
     * 		        	
     * 
     */
    @XmlEnumValue("SSBI-PR")
    SSBI_PR("SSBI-PR"),

    /**
     * 
     * 						NACI + credit check
     * 		        	
     * 
     */
    NACIC("NACIC"),

    /**
     * 
     * 						NAC with Local Agency Check and Credit (NACLC)
     * 		        	
     * 
     */
    NACLC("NACLC"),

    /**
     * 
     * 						Background Investigation
     * 		        	
     * 
     */
    BI("BI"),

    /**
     * 
     * 						Background Investigation
     * 		        	
     * 
     */
    MBI("MBI"),

    /**
     * 
     * 						Limited Background Investigation
     * 		        	
     * 
     */
    LBI("LBI"),

    /**
     * 
     *                         Tier 1: Low Risk, Non-Sensitive, inlcuding HSPD-12 Credentialing
     *                     
     * 
     */
    @XmlEnumValue("TIER1")
    TIER_1("TIER1"),

    /**
     * 
     *                         Tier 2: Moderate Risk Public Trust (MRPT)
     *                     
     * 
     */
    @XmlEnumValue("TIER2")
    TIER_2("TIER2"),

    /**
     * 
     *                         Tier 3: Non-Critical Sensitive, National Security, including SECRET and L access eligibility
     *                     
     * 
     */
    @XmlEnumValue("TIER3")
    TIER_3("TIER3"),

    /**
     * 
     *                         Tier 4: High Risk Public Trust (HRPT)
     *                     
     * 
     */
    @XmlEnumValue("TIER4")
    TIER_4("TIER4"),

    /**
     * 
     *                         Tier 5: Critical Sensitive and Special Sensitive National Security, including Top Secret, SCI, and Q access eligibility
     *                     
     * 
     */
    @XmlEnumValue("TIER5")
    TIER_5("TIER5");
    private final String value;

    PersonInvestigationCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PersonInvestigationCodeType fromValue(String v) {
        for (PersonInvestigationCodeType c: PersonInvestigationCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
