//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RequestId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="RequestCommitCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CardExtractedInfo" type="{http://hspd12.hhs.gov/piv/binding/v1}CardExtractedInformationType" minOccurs="0"/&gt;
 *         &lt;element name="CardPrintedInfo" type="{http://hspd12.hhs.gov/piv/binding/v1}PivModelCardPrintedInformationType" minOccurs="0"/&gt;
 *         &lt;element name="PivAuthenticationCertInfo" type="{http://hspd12.hhs.gov/piv/binding/v1}CardCertificateInfoType"/&gt;
 *         &lt;element name="PivDigitalSignatureCertInfo" type="{http://hspd12.hhs.gov/piv/binding/v1}CardCertificateInfoType" minOccurs="0"/&gt;
 *         &lt;element name="PivKeyManagementCertInfo" type="{http://hspd12.hhs.gov/piv/binding/v1}CardCertificateInfoType" minOccurs="0"/&gt;
 *         &lt;element name="PivCardAuthenticationCertInfo" type="{http://hspd12.hhs.gov/piv/binding/v1}CardCertificateInfoType" minOccurs="0"/&gt;
 *         &lt;element name="CardHolderFacialImageJpeg" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="ProcessingNotification" type="{http://hspd12.hhs.gov/piv/binding/v1}ProcessingNotificationType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ShowWarningNotification" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="WarningNotification" type="{http://hspd12.hhs.gov/piv/binding/v1}ProcessingNotificationType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ErrorNotification" type="{http://hspd12.hhs.gov/piv/binding/v1}ProcessingNotificationType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ResultCode"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Success"/&gt;
 *               &lt;enumeration value="ErrorDetected"/&gt;
 *               &lt;enumeration value="Failed"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FailureDetailMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestId",
    "requestCommitCode",
    "cardExtractedInfo",
    "cardPrintedInfo",
    "pivAuthenticationCertInfo",
    "pivDigitalSignatureCertInfo",
    "pivKeyManagementCertInfo",
    "pivCardAuthenticationCertInfo",
    "cardHolderFacialImageJpeg",
    "processingNotification",
    "showWarningNotification",
    "warningNotification",
    "errorNotification",
    "resultCode",
    "failureDetailMessage"
})
@XmlRootElement(name = "PrepareBindExternalCardResponse", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
public class PrepareBindExternalCardResponse {

    @XmlElement(name = "RequestId", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected Long requestId;
    @XmlElement(name = "RequestCommitCode", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected String requestCommitCode;
    @XmlElement(name = "CardExtractedInfo", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected CardExtractedInformationType cardExtractedInfo;
    @XmlElement(name = "CardPrintedInfo", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected PivModelCardPrintedInformationType cardPrintedInfo;
    @XmlElement(name = "PivAuthenticationCertInfo", namespace = "http://hspd12.hhs.gov/piv/binding/v1", required = true)
    protected CardCertificateInfoType pivAuthenticationCertInfo;
    @XmlElement(name = "PivDigitalSignatureCertInfo", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected CardCertificateInfoType pivDigitalSignatureCertInfo;
    @XmlElement(name = "PivKeyManagementCertInfo", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected CardCertificateInfoType pivKeyManagementCertInfo;
    @XmlElement(name = "PivCardAuthenticationCertInfo", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected CardCertificateInfoType pivCardAuthenticationCertInfo;
    @XmlElement(name = "CardHolderFacialImageJpeg", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected byte[] cardHolderFacialImageJpeg;
    @XmlElement(name = "ProcessingNotification", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected List<ProcessingNotificationType> processingNotification;
    @XmlElement(name = "ShowWarningNotification", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected Boolean showWarningNotification;
    @XmlElement(name = "WarningNotification", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected List<ProcessingNotificationType> warningNotification;
    @XmlElement(name = "ErrorNotification", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected List<ProcessingNotificationType> errorNotification;
    @XmlElement(name = "ResultCode", namespace = "http://hspd12.hhs.gov/piv/binding/v1", required = true)
    protected String resultCode;
    @XmlElement(name = "FailureDetailMessage", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected String failureDetailMessage;

    /**
     * Gets the value of the requestId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRequestId(Long value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the requestCommitCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestCommitCode() {
        return requestCommitCode;
    }

    /**
     * Sets the value of the requestCommitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestCommitCode(String value) {
        this.requestCommitCode = value;
    }

    /**
     * Gets the value of the cardExtractedInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CardExtractedInformationType }
     *     
     */
    public CardExtractedInformationType getCardExtractedInfo() {
        return cardExtractedInfo;
    }

    /**
     * Sets the value of the cardExtractedInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardExtractedInformationType }
     *     
     */
    public void setCardExtractedInfo(CardExtractedInformationType value) {
        this.cardExtractedInfo = value;
    }

    /**
     * Gets the value of the cardPrintedInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PivModelCardPrintedInformationType }
     *     
     */
    public PivModelCardPrintedInformationType getCardPrintedInfo() {
        return cardPrintedInfo;
    }

    /**
     * Sets the value of the cardPrintedInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PivModelCardPrintedInformationType }
     *     
     */
    public void setCardPrintedInfo(PivModelCardPrintedInformationType value) {
        this.cardPrintedInfo = value;
    }

    /**
     * Gets the value of the pivAuthenticationCertInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CardCertificateInfoType }
     *     
     */
    public CardCertificateInfoType getPivAuthenticationCertInfo() {
        return pivAuthenticationCertInfo;
    }

    /**
     * Sets the value of the pivAuthenticationCertInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardCertificateInfoType }
     *     
     */
    public void setPivAuthenticationCertInfo(CardCertificateInfoType value) {
        this.pivAuthenticationCertInfo = value;
    }

    /**
     * Gets the value of the pivDigitalSignatureCertInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CardCertificateInfoType }
     *     
     */
    public CardCertificateInfoType getPivDigitalSignatureCertInfo() {
        return pivDigitalSignatureCertInfo;
    }

    /**
     * Sets the value of the pivDigitalSignatureCertInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardCertificateInfoType }
     *     
     */
    public void setPivDigitalSignatureCertInfo(CardCertificateInfoType value) {
        this.pivDigitalSignatureCertInfo = value;
    }

    /**
     * Gets the value of the pivKeyManagementCertInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CardCertificateInfoType }
     *     
     */
    public CardCertificateInfoType getPivKeyManagementCertInfo() {
        return pivKeyManagementCertInfo;
    }

    /**
     * Sets the value of the pivKeyManagementCertInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardCertificateInfoType }
     *     
     */
    public void setPivKeyManagementCertInfo(CardCertificateInfoType value) {
        this.pivKeyManagementCertInfo = value;
    }

    /**
     * Gets the value of the pivCardAuthenticationCertInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CardCertificateInfoType }
     *     
     */
    public CardCertificateInfoType getPivCardAuthenticationCertInfo() {
        return pivCardAuthenticationCertInfo;
    }

    /**
     * Sets the value of the pivCardAuthenticationCertInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardCertificateInfoType }
     *     
     */
    public void setPivCardAuthenticationCertInfo(CardCertificateInfoType value) {
        this.pivCardAuthenticationCertInfo = value;
    }

    /**
     * Gets the value of the cardHolderFacialImageJpeg property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCardHolderFacialImageJpeg() {
        return cardHolderFacialImageJpeg;
    }

    /**
     * Sets the value of the cardHolderFacialImageJpeg property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCardHolderFacialImageJpeg(byte[] value) {
        this.cardHolderFacialImageJpeg = value;
    }

    /**
     * Gets the value of the processingNotification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processingNotification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessingNotification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessingNotificationType }
     * 
     * 
     */
    public List<ProcessingNotificationType> getProcessingNotification() {
        if (processingNotification == null) {
            processingNotification = new ArrayList<ProcessingNotificationType>();
        }
        return this.processingNotification;
    }

    /**
     * Gets the value of the showWarningNotification property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowWarningNotification() {
        return showWarningNotification;
    }

    /**
     * Sets the value of the showWarningNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowWarningNotification(Boolean value) {
        this.showWarningNotification = value;
    }

    /**
     * Gets the value of the warningNotification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the warningNotification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWarningNotification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessingNotificationType }
     * 
     * 
     */
    public List<ProcessingNotificationType> getWarningNotification() {
        if (warningNotification == null) {
            warningNotification = new ArrayList<ProcessingNotificationType>();
        }
        return this.warningNotification;
    }

    /**
     * Gets the value of the errorNotification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the errorNotification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErrorNotification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessingNotificationType }
     * 
     * 
     */
    public List<ProcessingNotificationType> getErrorNotification() {
        if (errorNotification == null) {
            errorNotification = new ArrayList<ProcessingNotificationType>();
        }
        return this.errorNotification;
    }

    /**
     * Gets the value of the resultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * Sets the value of the resultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultCode(String value) {
        this.resultCode = value;
    }

    /**
     * Gets the value of the failureDetailMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFailureDetailMessage() {
        return failureDetailMessage;
    }

    /**
     * Sets the value of the failureDetailMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFailureDetailMessage(String value) {
        this.failureDetailMessage = value;
    }

}
