//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="WantCardHolderFacialImageJpeg" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ApplicantPI" type="{http://hspd12.hhs.gov/piv/binding/v1}PersonIdType"/&gt;
 *         &lt;element name="SubmitterPI" type="{http://hspd12.hhs.gov/piv/binding/v1}PersonIdType"/&gt;
 *         &lt;element name="EwsResourceTag" type="{http://hspd12.hhs.gov/piv/binding/v1}ResourceTagType"/&gt;
 *         &lt;element name="EwsSiteTag" type="{http://hspd12.hhs.gov/piv/binding/v1}SiteTagType"/&gt;
 *         &lt;element name="CardCIN" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="50"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CardATR" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="66"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CardIIN" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="15"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CardCapabilityContainerCont" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *         &lt;element name="CardHolderUniqueIdCont" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *         &lt;element name="SecurityObjectCont" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *         &lt;element name="DiscoveryObjectCont" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="KeyHistoryObjectCont" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="CardPrintedInfoCont" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="CardHolderFingerprintsCont" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *         &lt;element name="CardHolderFacialImageCont" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="CardHolderIrisImageCont" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="PivAuthenticationCertCont" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *         &lt;element name="PivDigitalSignatureCertCont" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="PivKeyManagementCertCont" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="PivCardAuthenticationCertCont" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "wantCardHolderFacialImageJpeg",
    "applicantPI",
    "submitterPI",
    "ewsResourceTag",
    "ewsSiteTag",
    "cardCIN",
    "cardATR",
    "cardIIN",
    "cardCapabilityContainerCont",
    "cardHolderUniqueIdCont",
    "securityObjectCont",
    "discoveryObjectCont",
    "keyHistoryObjectCont",
    "cardPrintedInfoCont",
    "cardHolderFingerprintsCont",
    "cardHolderFacialImageCont",
    "cardHolderIrisImageCont",
    "pivAuthenticationCertCont",
    "pivDigitalSignatureCertCont",
    "pivKeyManagementCertCont",
    "pivCardAuthenticationCertCont"
})
@XmlRootElement(name = "PrepareBindExternalCardRequest", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
public class PrepareBindExternalCardRequest {

    @XmlElement(name = "WantCardHolderFacialImageJpeg", namespace = "http://hspd12.hhs.gov/piv/binding/v1", defaultValue = "false")
    protected Boolean wantCardHolderFacialImageJpeg;
    @XmlElement(name = "ApplicantPI", namespace = "http://hspd12.hhs.gov/piv/binding/v1", required = true)
    protected String applicantPI;
    @XmlElement(name = "SubmitterPI", namespace = "http://hspd12.hhs.gov/piv/binding/v1", required = true)
    protected String submitterPI;
    @XmlElement(name = "EwsResourceTag", namespace = "http://hspd12.hhs.gov/piv/binding/v1", required = true)
    protected String ewsResourceTag;
    @XmlElement(name = "EwsSiteTag", namespace = "http://hspd12.hhs.gov/piv/binding/v1", required = true)
    protected String ewsSiteTag;
    @XmlElement(name = "CardCIN", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected String cardCIN;
    @XmlElement(name = "CardATR", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected String cardATR;
    @XmlElement(name = "CardIIN", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected String cardIIN;
    @XmlElement(name = "CardCapabilityContainerCont", namespace = "http://hspd12.hhs.gov/piv/binding/v1", required = true)
    protected byte[] cardCapabilityContainerCont;
    @XmlElement(name = "CardHolderUniqueIdCont", namespace = "http://hspd12.hhs.gov/piv/binding/v1", required = true)
    protected byte[] cardHolderUniqueIdCont;
    @XmlElement(name = "SecurityObjectCont", namespace = "http://hspd12.hhs.gov/piv/binding/v1", required = true)
    protected byte[] securityObjectCont;
    @XmlElement(name = "DiscoveryObjectCont", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected byte[] discoveryObjectCont;
    @XmlElement(name = "KeyHistoryObjectCont", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected byte[] keyHistoryObjectCont;
    @XmlElement(name = "CardPrintedInfoCont", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected byte[] cardPrintedInfoCont;
    @XmlElement(name = "CardHolderFingerprintsCont", namespace = "http://hspd12.hhs.gov/piv/binding/v1", required = true)
    protected byte[] cardHolderFingerprintsCont;
    @XmlElement(name = "CardHolderFacialImageCont", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected byte[] cardHolderFacialImageCont;
    @XmlElement(name = "CardHolderIrisImageCont", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected byte[] cardHolderIrisImageCont;
    @XmlElement(name = "PivAuthenticationCertCont", namespace = "http://hspd12.hhs.gov/piv/binding/v1", required = true)
    protected byte[] pivAuthenticationCertCont;
    @XmlElement(name = "PivDigitalSignatureCertCont", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected byte[] pivDigitalSignatureCertCont;
    @XmlElement(name = "PivKeyManagementCertCont", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected byte[] pivKeyManagementCertCont;
    @XmlElement(name = "PivCardAuthenticationCertCont", namespace = "http://hspd12.hhs.gov/piv/binding/v1")
    protected byte[] pivCardAuthenticationCertCont;

    /**
     * Gets the value of the wantCardHolderFacialImageJpeg property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWantCardHolderFacialImageJpeg() {
        return wantCardHolderFacialImageJpeg;
    }

    /**
     * Sets the value of the wantCardHolderFacialImageJpeg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWantCardHolderFacialImageJpeg(Boolean value) {
        this.wantCardHolderFacialImageJpeg = value;
    }

    /**
     * Gets the value of the applicantPI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicantPI() {
        return applicantPI;
    }

    /**
     * Sets the value of the applicantPI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicantPI(String value) {
        this.applicantPI = value;
    }

    /**
     * Gets the value of the submitterPI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubmitterPI() {
        return submitterPI;
    }

    /**
     * Sets the value of the submitterPI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubmitterPI(String value) {
        this.submitterPI = value;
    }

    /**
     * Gets the value of the ewsResourceTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEwsResourceTag() {
        return ewsResourceTag;
    }

    /**
     * Sets the value of the ewsResourceTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEwsResourceTag(String value) {
        this.ewsResourceTag = value;
    }

    /**
     * Gets the value of the ewsSiteTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEwsSiteTag() {
        return ewsSiteTag;
    }

    /**
     * Sets the value of the ewsSiteTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEwsSiteTag(String value) {
        this.ewsSiteTag = value;
    }

    /**
     * Gets the value of the cardCIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardCIN() {
        return cardCIN;
    }

    /**
     * Sets the value of the cardCIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardCIN(String value) {
        this.cardCIN = value;
    }

    /**
     * Gets the value of the cardATR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardATR() {
        return cardATR;
    }

    /**
     * Sets the value of the cardATR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardATR(String value) {
        this.cardATR = value;
    }

    /**
     * Gets the value of the cardIIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardIIN() {
        return cardIIN;
    }

    /**
     * Sets the value of the cardIIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardIIN(String value) {
        this.cardIIN = value;
    }

    /**
     * Gets the value of the cardCapabilityContainerCont property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCardCapabilityContainerCont() {
        return cardCapabilityContainerCont;
    }

    /**
     * Sets the value of the cardCapabilityContainerCont property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCardCapabilityContainerCont(byte[] value) {
        this.cardCapabilityContainerCont = value;
    }

    /**
     * Gets the value of the cardHolderUniqueIdCont property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCardHolderUniqueIdCont() {
        return cardHolderUniqueIdCont;
    }

    /**
     * Sets the value of the cardHolderUniqueIdCont property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCardHolderUniqueIdCont(byte[] value) {
        this.cardHolderUniqueIdCont = value;
    }

    /**
     * Gets the value of the securityObjectCont property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getSecurityObjectCont() {
        return securityObjectCont;
    }

    /**
     * Sets the value of the securityObjectCont property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setSecurityObjectCont(byte[] value) {
        this.securityObjectCont = value;
    }

    /**
     * Gets the value of the discoveryObjectCont property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getDiscoveryObjectCont() {
        return discoveryObjectCont;
    }

    /**
     * Sets the value of the discoveryObjectCont property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setDiscoveryObjectCont(byte[] value) {
        this.discoveryObjectCont = value;
    }

    /**
     * Gets the value of the keyHistoryObjectCont property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getKeyHistoryObjectCont() {
        return keyHistoryObjectCont;
    }

    /**
     * Sets the value of the keyHistoryObjectCont property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setKeyHistoryObjectCont(byte[] value) {
        this.keyHistoryObjectCont = value;
    }

    /**
     * Gets the value of the cardPrintedInfoCont property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCardPrintedInfoCont() {
        return cardPrintedInfoCont;
    }

    /**
     * Sets the value of the cardPrintedInfoCont property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCardPrintedInfoCont(byte[] value) {
        this.cardPrintedInfoCont = value;
    }

    /**
     * Gets the value of the cardHolderFingerprintsCont property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCardHolderFingerprintsCont() {
        return cardHolderFingerprintsCont;
    }

    /**
     * Sets the value of the cardHolderFingerprintsCont property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCardHolderFingerprintsCont(byte[] value) {
        this.cardHolderFingerprintsCont = value;
    }

    /**
     * Gets the value of the cardHolderFacialImageCont property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCardHolderFacialImageCont() {
        return cardHolderFacialImageCont;
    }

    /**
     * Sets the value of the cardHolderFacialImageCont property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCardHolderFacialImageCont(byte[] value) {
        this.cardHolderFacialImageCont = value;
    }

    /**
     * Gets the value of the cardHolderIrisImageCont property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCardHolderIrisImageCont() {
        return cardHolderIrisImageCont;
    }

    /**
     * Sets the value of the cardHolderIrisImageCont property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCardHolderIrisImageCont(byte[] value) {
        this.cardHolderIrisImageCont = value;
    }

    /**
     * Gets the value of the pivAuthenticationCertCont property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPivAuthenticationCertCont() {
        return pivAuthenticationCertCont;
    }

    /**
     * Sets the value of the pivAuthenticationCertCont property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPivAuthenticationCertCont(byte[] value) {
        this.pivAuthenticationCertCont = value;
    }

    /**
     * Gets the value of the pivDigitalSignatureCertCont property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPivDigitalSignatureCertCont() {
        return pivDigitalSignatureCertCont;
    }

    /**
     * Sets the value of the pivDigitalSignatureCertCont property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPivDigitalSignatureCertCont(byte[] value) {
        this.pivDigitalSignatureCertCont = value;
    }

    /**
     * Gets the value of the pivKeyManagementCertCont property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPivKeyManagementCertCont() {
        return pivKeyManagementCertCont;
    }

    /**
     * Sets the value of the pivKeyManagementCertCont property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPivKeyManagementCertCont(byte[] value) {
        this.pivKeyManagementCertCont = value;
    }

    /**
     * Gets the value of the pivCardAuthenticationCertCont property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPivCardAuthenticationCertCont() {
        return pivCardAuthenticationCertCont;
    }

    /**
     * Sets the value of the pivCardAuthenticationCertCont property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPivCardAuthenticationCertCont(byte[] value) {
        this.pivCardAuthenticationCertCont = value;
    }

}
