//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StateCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StateCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AK"/&gt;
 *     &lt;enumeration value="AL"/&gt;
 *     &lt;enumeration value="AM"/&gt;
 *     &lt;enumeration value="AR"/&gt;
 *     &lt;enumeration value="AZ"/&gt;
 *     &lt;enumeration value="BK"/&gt;
 *     &lt;enumeration value="CA"/&gt;
 *     &lt;enumeration value="CG"/&gt;
 *     &lt;enumeration value="CO"/&gt;
 *     &lt;enumeration value="CT"/&gt;
 *     &lt;enumeration value="CZ"/&gt;
 *     &lt;enumeration value="DC"/&gt;
 *     &lt;enumeration value="DE"/&gt;
 *     &lt;enumeration value="FL"/&gt;
 *     &lt;enumeration value="GA"/&gt;
 *     &lt;enumeration value="GM"/&gt;
 *     &lt;enumeration value="HI"/&gt;
 *     &lt;enumeration value="HO"/&gt;
 *     &lt;enumeration value="IA"/&gt;
 *     &lt;enumeration value="ID"/&gt;
 *     &lt;enumeration value="IL"/&gt;
 *     &lt;enumeration value="IN"/&gt;
 *     &lt;enumeration value="JI"/&gt;
 *     &lt;enumeration value="JR"/&gt;
 *     &lt;enumeration value="KI"/&gt;
 *     &lt;enumeration value="KS"/&gt;
 *     &lt;enumeration value="KY"/&gt;
 *     &lt;enumeration value="LA"/&gt;
 *     &lt;enumeration value="MA"/&gt;
 *     &lt;enumeration value="MD"/&gt;
 *     &lt;enumeration value="ME"/&gt;
 *     &lt;enumeration value="MH"/&gt;
 *     &lt;enumeration value="MI"/&gt;
 *     &lt;enumeration value="MK"/&gt;
 *     &lt;enumeration value="MN"/&gt;
 *     &lt;enumeration value="MO"/&gt;
 *     &lt;enumeration value="MS"/&gt;
 *     &lt;enumeration value="MT"/&gt;
 *     &lt;enumeration value="MW"/&gt;
 *     &lt;enumeration value="NB"/&gt;
 *     &lt;enumeration value="NC"/&gt;
 *     &lt;enumeration value="ND"/&gt;
 *     &lt;enumeration value="NH"/&gt;
 *     &lt;enumeration value="NJ"/&gt;
 *     &lt;enumeration value="NM"/&gt;
 *     &lt;enumeration value="NV"/&gt;
 *     &lt;enumeration value="NY"/&gt;
 *     &lt;enumeration value="OH"/&gt;
 *     &lt;enumeration value="OK"/&gt;
 *     &lt;enumeration value="OR"/&gt;
 *     &lt;enumeration value="PA"/&gt;
 *     &lt;enumeration value="PL"/&gt;
 *     &lt;enumeration value="PR"/&gt;
 *     &lt;enumeration value="RI"/&gt;
 *     &lt;enumeration value="SC"/&gt;
 *     &lt;enumeration value="SD"/&gt;
 *     &lt;enumeration value="TN"/&gt;
 *     &lt;enumeration value="TX"/&gt;
 *     &lt;enumeration value="UT"/&gt;
 *     &lt;enumeration value="VA"/&gt;
 *     &lt;enumeration value="VI"/&gt;
 *     &lt;enumeration value="VT"/&gt;
 *     &lt;enumeration value="WA"/&gt;
 *     &lt;enumeration value="WI"/&gt;
 *     &lt;enumeration value="WK"/&gt;
 *     &lt;enumeration value="WV"/&gt;
 *     &lt;enumeration value="WY"/&gt;
 *     &lt;enumeration value="XX"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "StateCodeType")
@XmlEnum
public enum StateCodeType {

    AK,
    AL,
    AM,
    AR,
    AZ,
    BK,
    CA,
    CG,
    CO,
    CT,
    CZ,
    DC,
    DE,
    FL,
    GA,
    GM,
    HI,
    HO,
    IA,
    ID,
    IL,
    IN,
    JI,
    JR,
    KI,
    KS,
    KY,
    LA,
    MA,
    MD,
    ME,
    MH,
    MI,
    MK,
    MN,
    MO,
    MS,
    MT,
    MW,
    NB,
    NC,
    ND,
    NH,
    NJ,
    NM,
    NV,
    NY,
    OH,
    OK,
    OR,
    PA,
    PL,
    PR,
    RI,
    SC,
    SD,
    TN,
    TX,
    UT,
    VA,
    VI,
    VT,
    WA,
    WI,
    WK,
    WV,
    WY,
    XX;

    public String value() {
        return name();
    }

    public static StateCodeType fromValue(String v) {
        return valueOf(v);
    }

}
