//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TempCardIssueReasonCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TempCardIssueReasonCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="FORGOTTEN"/&gt;
 *     &lt;enumeration value="LSD"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TempCardIssueReasonCodeType")
@XmlEnum
public enum TempCardIssueReasonCodeType {


    /**
     * 
     *                         Temp card issued because HHS employee forgot PIV card
     *                     
     * 
     */
    FORGOTTEN,

    /**
     * 
     *                         Temp card issued because HHS employee's PIV card was either
     *                         lost, stolen, or damaged.
     *                     
     * 
     */
    LSD;

    public String value() {
        return name();
    }

    public static TempCardIssueReasonCodeType fromValue(String v) {
        return valueOf(v);
    }

}
