//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 				This type defines a type safe container for storing 
 * 				several common types of data.
 * 			
 * 
 * <p>Java class for TypedValueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TypedValueType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="BoolVal" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="IntVal" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="DateTimeVal" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="StringVal" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DoubleVal" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="BinaryVal" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TypedValueType", namespace = "http://hspd12.hhs.gov/piv/binding/v1", propOrder = {
    "boolVal",
    "intVal",
    "dateTimeVal",
    "stringVal",
    "doubleVal",
    "binaryVal"
})
public class TypedValueType {

    @XmlElement(name = "BoolVal")
    protected Boolean boolVal;
    @XmlElement(name = "IntVal")
    protected Integer intVal;
    @XmlElement(name = "DateTimeVal")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateTimeVal;
    @XmlElement(name = "StringVal")
    protected String stringVal;
    @XmlElement(name = "DoubleVal")
    protected Double doubleVal;
    @XmlElement(name = "BinaryVal")
    protected byte[] binaryVal;

    /**
     * Gets the value of the boolVal property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBoolVal() {
        return boolVal;
    }

    /**
     * Sets the value of the boolVal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBoolVal(Boolean value) {
        this.boolVal = value;
    }

    /**
     * Gets the value of the intVal property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIntVal() {
        return intVal;
    }

    /**
     * Sets the value of the intVal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIntVal(Integer value) {
        this.intVal = value;
    }

    /**
     * Gets the value of the dateTimeVal property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTimeVal() {
        return dateTimeVal;
    }

    /**
     * Sets the value of the dateTimeVal property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTimeVal(XMLGregorianCalendar value) {
        this.dateTimeVal = value;
    }

    /**
     * Gets the value of the stringVal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStringVal() {
        return stringVal;
    }

    /**
     * Sets the value of the stringVal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStringVal(String value) {
        this.stringVal = value;
    }

    /**
     * Gets the value of the doubleVal property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDoubleVal() {
        return doubleVal;
    }

    /**
     * Sets the value of the doubleVal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDoubleVal(Double value) {
        this.doubleVal = value;
    }

    /**
     * Gets the value of the binaryVal property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getBinaryVal() {
        return binaryVal;
    }

    /**
     * Sets the value of the binaryVal property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setBinaryVal(byte[] value) {
        this.binaryVal = value;
    }

}
