//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 11:07:08 PM EST 
//


package gov.hhs.induction.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TransactionHeader" type="{http://hspd12.hhs.gov/federated/enrollment/v1}TransactionHeaderType"/&gt;
 *         &lt;element name="eventType" type="{http://hspd12.hhs.gov/federated/enrollment/v1}IdmsEventNotifyType" minOccurs="0"/&gt;
 *         &lt;element name="agencyAcronym" type="{http://hspd12.hhs.gov/federated/enrollment/v1}OpdivCodeType"/&gt;
 *         &lt;element name="NotifyURL" type="{http://hspd12.hhs.gov/federated/enrollment/v1}EventNotifyURLType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transactionHeader",
    "eventType",
    "agencyAcronym",
    "notifyURL"
})
@XmlRootElement(name = "UnSubscribeIdmsEventsRequest")
public class UnSubscribeIdmsEventsRequest {

    @XmlElement(name = "TransactionHeader", required = true)
    protected TransactionHeaderType transactionHeader;
    @XmlSchemaType(name = "string")
    protected IdmsEventNotifyType eventType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected OpdivCodeType agencyAcronym;
    @XmlElement(name = "NotifyURL", required = true)
    protected String notifyURL;

    /**
     * Gets the value of the transactionHeader property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionHeaderType }
     *     
     */
    public TransactionHeaderType getTransactionHeader() {
        return transactionHeader;
    }

    /**
     * Sets the value of the transactionHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionHeaderType }
     *     
     */
    public void setTransactionHeader(TransactionHeaderType value) {
        this.transactionHeader = value;
    }

    /**
     * Gets the value of the eventType property.
     * 
     * @return
     *     possible object is
     *     {@link IdmsEventNotifyType }
     *     
     */
    public IdmsEventNotifyType getEventType() {
        return eventType;
    }

    /**
     * Sets the value of the eventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdmsEventNotifyType }
     *     
     */
    public void setEventType(IdmsEventNotifyType value) {
        this.eventType = value;
    }

    /**
     * Gets the value of the agencyAcronym property.
     * 
     * @return
     *     possible object is
     *     {@link OpdivCodeType }
     *     
     */
    public OpdivCodeType getAgencyAcronym() {
        return agencyAcronym;
    }

    /**
     * Sets the value of the agencyAcronym property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpdivCodeType }
     *     
     */
    public void setAgencyAcronym(OpdivCodeType value) {
        this.agencyAcronym = value;
    }

    /**
     * Gets the value of the notifyURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotifyURL() {
        return notifyURL;
    }

    /**
     * Sets the value of the notifyURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotifyURL(String value) {
        this.notifyURL = value;
    }

}
