

----------------------------------
-- grant for HHS_WHRSC_HR_RW_ROLE
----------------------------------

GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.DSS_VACANCY TO HHS_WHRSC_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.DSS_NEW_HIRE_VACANCY_REQUEST TO HHS_WHRSC_HR_RW_ROLE;