----------------------------------
-- grant for HHS_WHRSC_HR_RW_ROLE
----------------------------------

GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_VACANCY TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_NEW_HIRE_VACNCY_REQ TO HHS_WHRSC_HR_RW_ROLE;