SET DEFINE OFF;

ALTER TABLE RECRUITMENT ADD SHARED_ANN_REVIEWED VARCHAR2(1000);

ALTER TABLE APPOINTMENT ADD EXTERNAL_CERT_NUMBER  VARCHAR2(40);
ALTER TABLE APPOINTMENT ADD CERTIFICATE_DETAILS VARCHAR2(220);
ALTER TABLE APPOINTMENT ADD EXTERNAL_CERT_ANN_NUMBER VARCHAR2(40);
ALTER TABLE APPOINTMENT ADD EXTERNAL_CERT_POS_TITLE VARCHAR2(100);
ALTER TABLE APPOINTMENT ADD EXTERNAL_CERT_GRADE VARCHAR2(30);

