SET DEFINE OFF;

ALTER TABLE RECRUITMENT ADD SHARED_ANN_REVIEWED VARCHAR2(1000);

ALTER TABLE APPOINTMENT ADD EXTERNAL_CERT_NUMBER  VARCHAR2(40);
ALTER TABLE APPOINTMENT ADD CERTIFICATE_DETAILS VARCHAR2(220);
ALTER TABLE APPOINTMENT ADD EXTERNAL_CERT_ANN_NUMBER VARCHAR2(40);
ALTER TABLE APPOINTMENT ADD EXTERNAL_CERT_POS_TITLE VARCHAR2(100);
ALTER TABLE APPOINTMENT ADD EXTERNAL_CERT_GRADE VARCHAR2(30);

--Create Temporary table for CHR_PROCESSED_JOBS
CREATE TABLE CHR_PROCESSED_JOBS_NEW
(
  JOB_ID VARCHAR2(30), 
        EFFDT DATE, 
        DATE_PROCESSED_IN_CAPHR DATE
);
 
ALTER TABLE "HHS_WHRSC_HR"."CHR_PROCESSED_JOBS_NEW" MODIFY ("DATE_PROCESSED_IN_CAPHR" NOT NULL ENABLE);
ALTER TABLE "HHS_WHRSC_HR"."CHR_PROCESSED_JOBS_NEW" MODIFY ("JOB_ID" NOT NULL ENABLE);
 
--Insert data from CHR_PROCESS_JOBS to temporary table
  INSERT INTO CHR_PROCESSED_JOBS_NEW 
  SELECT * FROM CHR_PROCESSED_JOBS;
 
--Rename CHR_PROCESSED_JOBS table  
  ALTER TABLE CHR_PROCESSED_JOBS 
  RENAME TO CHR_PROCESSED_JOBS_OLD;
 
--Rename temporary table to CHR_PROCESSED_JOBS  
  ALTER TABLE CHR_PROCESSED_JOBS_NEW 
  RENAME TO CHR_PROCESSED_JOBS;
 
--Drop CHR_PROCESSED_JOBS_OLD table  
DROP TABLE CHR_PROCESSED_JOBS_OLD;
