----------------------------------
-- grant for HHS_WHRSC_HR_RW_ROLE
----------------------------------

GRANT SELECT ON HHS_WHRSC_HR.VW_R_VAC_ANN_RESULT TO HHS_WHRSC_HR_RW_ROLE;

GRANT SELECT ON HHS_WHRSC_HR.VW_R_VAC_POS_RESULT TO HHS_WHRSC_HR_RW_ROLE;

GRANT SELECT ON HHS_WHRSC_HR.VW_R_APPLICANTS_RESULT TO HHS_WHRSC_HR_RW_ROLE;

GRANT SELECT ON HHS_WHRSC_HR.VW_R_CERT_RESULT TO HHS_WHRSC_HR_RW_ROLE;

GRANT SELECT ON HHS_WHRSC_HR.VW_R_POS_RESULT TO HHS_WHRSC_HR_RW_ROLE;

GRANT SELECT ON HHS_WHRSC_HR.VW_R_REQ_POS_RESULT TO HHS_WHRSC_HR_RW_ROLE;

GRANT SELECT ON HHS_WHRSC_HR.VW_A_VAC_ANN_RESULT TO HHS_WHRSC_HR_RW_ROLE;

GRANT SELECT ON HHS_WHRSC_HR.VW_A_CERT_RESULT TO HHS_WHRSC_HR_RW_ROLE;

GRANT SELECT ON HHS_WHRSC_HR.VW_A_DUTY_LOC_RESULT TO HHS_WHRSC_HR_RW_ROLE;