--------------------------------
-- DDL FOR RECRUITMENT VIEWS           
--------------------------------
--------------------------------

---------------------
--VW_R_VAC_ANN_RESULT
---------------------
CREATE OR REPLACE VIEW HHS_WHRSC_HR.VW_R_VAC_ANN_RESULT
AS
SELECT
	REQUEST_NUMBER || TO_CHAR(VACANCY_NUMBER) AS REQ_VAC,
	REQUEST_NUMBER,
	TO_CHAR(VACANCY_NUMBER) AS VACANCY_NUMBER,
	CASE
		WHEN NUMBER_OF_POSITIONS_ADVERTISED IS NULL
		THEN '-'
		ELSE NUMBER_OF_POSITIONS_ADVERTISED
	END AS NUMBER_OF_POSITIONS_ADVERTISED,
	LISTAGG(VACANCY_ELIGIBILITY, '; ')
		WITHIN GROUP(ORDER BY VACANCY_NUMBER) AS AREA_OF_CONSIDERATION,
	CASE
		WHEN COUNT(DISTINCT SERIES) > 1
			THEN 'Yes'
			ELSE 'No'
		END AS INTERDISCIPLINARY_POSITION,
	VACANCY_ANNOUNCEMENT_NUMBER,
	CASE
		WHEN ANNOUNCEMENT_TYPE LIKE '%DE%'
		THEN 'DE'
		ELSE ANNOUNCEMENT_TYPE
	END AS ANNOUNCEMENT_TYPE,
	DATE_ANNOUNCEMENT_POSTED,
	DATE_ANNOUNCEMENT_OPENED,
	DATE_ANNOUNCEMENT_CLOSED,
	DATE_ANNOUNCEMENT_CANCELLED
FROM
(
	SELECT
		DISTINCT ELG.VACANCY_ELIGIBILITY,
		COMBO.REQUEST_NUMBER,
		VAC.NUMBER_OF_POSITIONS_ADVERTISED,
		RTNG.SERIES,
		COMBO.VACANCY_NUMBER,
		VAC.VACANCY_ANNOUNCEMENT_NUMBER,
		VAC.ANNOUNCEMENT_TYPE,
		VAC.DATE_ANNOUNCEMENT_POSTED,
		VAC.DATE_ANNOUNCEMENT_OPENED,
		VAC.DATE_ANNOUNCEMENT_CLOSED,
		CASE
			WHEN VAC.VACANCY_STATUS = 'Cancelled'
			THEN VAC.LAST_UPDATE_DATE
			ELSE NULL
		END AS DATE_ANNOUNCEMENT_CANCELLED
	FROM HHS_WHRSC_HR.DSS_REQUEST_VACNCY_COMBINATION COMBO
		LEFT JOIN HHS_WHRSC_HR.DSS_VACANCY VAC
			ON COMBO.VACANCY_NUMBER = VAC.VACANCY_IDENTIFICATION_NUMBER
		LEFT JOIN HHS_WHRSC_HR.DSS_VACANCY_ELIGIBILITIES ELG
			ON COMBO.VACANCY_NUMBER = ELG.VACANCY_IDENTIFICATION_NUMBER
		LEFT JOIN HHS_WHRSC_HR.DSS_VACANCY_RATING_COMBINATION RTNG
			ON COMBO.VACANCY_NUMBER = RTNG.VACANCY_IDENTIFICATION_NUMBER
)
GROUP BY
	REQUEST_NUMBER || VACANCY_NUMBER,
	REQUEST_NUMBER,
	NUMBER_OF_POSITIONS_ADVERTISED,
	VACANCY_NUMBER,
	VACANCY_ANNOUNCEMENT_NUMBER,
	ANNOUNCEMENT_TYPE,
	DATE_ANNOUNCEMENT_POSTED,
	DATE_ANNOUNCEMENT_OPENED,
	DATE_ANNOUNCEMENT_CLOSED,
	DATE_ANNOUNCEMENT_CANCELLED;


--------------------------
--VW_R_VAC_POS_RESULT
--------------------------
CREATE OR REPLACE VIEW HHS_WHRSC_HR.VW_R_VAC_POS_RESULT
AS
SELECT
	REQUEST_NUMBER || TO_CHAR(VACANCY_NUMBER) AS REQ_VAC,
	REQUEST_NUMBER,
	TO_CHAR(VACANCY_NUMBER) AS VACANCY_NUMBER,
	POSITION_TITLE,
	REGEXP_REPLACE(LISTAGG(PAY_PLAN, ',')
		WITHIN GROUP(ORDER BY PAY_PLAN),'([^,]*)(,\1)+($|,)','\1\3') AS PAY_PLAN,
	REGEXP_REPLACE(LISTAGG(SERIES, ',')
		WITHIN GROUP(ORDER BY SERIES),'([^,]*)(,\1)+($|,)','\1\3') AS SERIES,
	REGEXP_REPLACE(LISTAGG(GRADE, ',')
		WITHIN GROUP(ORDER BY GRADE + 0),'([^,]*)(,\1)+($|,)','\1\3') AS GRADE,
	FULL_PERFORMANCE_LEVEL,
	REGEXP_REPLACE(LISTAGG(DUTY_LOCATION, ';')
		WITHIN GROUP(ORDER BY DUTY_LOCATION),'([^;]*)(;\1)+($|;)','\1\3') AS DUTY_LOCATION
FROM
(
	SELECT
		DISTINCT
		COMBO.REQUEST_NUMBER,
		COMBO.VACANCY_NUMBER,
		VAC.POSITION_TITLE,
		RTNG.PAY_PLAN,
		RTNG.SERIES,
		RTNG.GRADE,
		VAC.FULL_PERFORMANCE_LEVEL,
		CASE
			WHEN LOC.LOCATION_CITY IS NOT NULL
			THEN LOC.LOCATION_CITY || ', ' || LOC.LOCATION_STATE_ABBR || ' ' || LOC.LOCATION_COUNTRY
		END AS DUTY_LOCATION
	FROM DSS_REQUEST_VACNCY_COMBINATION COMBO
		LEFT JOIN DSS_VACANCY VAC
			ON COMBO.VACANCY_NUMBER = VAC.VACANCY_IDENTIFICATION_NUMBER
		LEFT JOIN DSS_VACANCY_RATING_COMBINATION RTNG
			ON COMBO.VACANCY_NUMBER = RTNG.VACANCY_IDENTIFICATION_NUMBER
		LEFT JOIN DSS_VACANCY_LOCATIONS LOC
			ON COMBO.VACANCY_NUMBER = LOC.VACANCY_IDENTIFICATION_NUMBER
)
GROUP BY
	REQUEST_NUMBER || VACANCY_NUMBER,
	REQUEST_NUMBER,
	VACANCY_NUMBER,
	POSITION_TITLE,
	FULL_PERFORMANCE_LEVEL;
	
--------------------------
--VW_R_APPLICANTS_RESULT
--------------------------
CREATE OR REPLACE VIEW HHS_WHRSC_HR.VW_R_APPLICANTS_RESULT
AS
SELECT
	REQUEST_NUMBER || TO_CHAR(COMBO.VACANCY_NUMBER) AS REQ_VAC,
	COMBO.REQUEST_NUMBER AS REQUEST_NUMBER,
	TO_CHAR(COMBO.VACANCY_NUMBER) AS VACANCY_NUMBER,
	VAC.VACANCY_ANNOUNCEMENT_NUMBER AS VACANCY_ANNOUNCEMENT_NUMBER,
	TO_CHAR(VAC.TOTAL_APPLICANTS) AS TOTAL_APPLICANTS,
	TO_CHAR(VAC.TOTAL_ELIGIBLE_APPLICANTS) AS TOTAL_ELIGIBLE_APPLICANTS,
	TO_CHAR(VAC.TOTAL_REFERRED_APPLICANTS) AS TOTAL_REFERRED_APPLICANTS,
	MIN(CASE 
			WHEN APP.APPLICATN_NOTIFICATN_TEMPLATE = 'Notice of Results'
			THEN INITIAL_NOTIFICATION_SEND_DATE
		END) AS DATE_APP_NOTFD_ELG_STATUS,
	MIN(CASE 
		WHEN APP.APPLICATN_NOTIFICATN_TEMPLATE = 'Notice of Referral'
		THEN INITIAL_NOTIFICATION_SEND_DATE
	END) AS DATE_APP_NOTFD_RFRL_STATUS
FROM HHS_WHRSC_HR.DSS_REQUEST_VACNCY_COMBINATION COMBO
	LEFT JOIN HHS_WHRSC_HR.DSS_VACANCY VAC
		ON COMBO.VACANCY_NUMBER = VAC.VACANCY_IDENTIFICATION_NUMBER
	LEFT JOIN HHS_WHRSC_HR.DSS_APPLICANT_NOTIFICATIONS APP
		ON COMBO.VACANCY_NUMBER = APP.VACANCY_NUMBER
GROUP BY
	REQUEST_NUMBER || COMBO.VACANCY_NUMBER,
	REQUEST_NUMBER,
	COMBO.VACANCY_NUMBER,
	VACANCY_ANNOUNCEMENT_NUMBER,
	TOTAL_APPLICANTS,
	TOTAL_ELIGIBLE_APPLICANTS,
	TOTAL_REFERRED_APPLICANTS;
	
--------------------------
--VW_R_CERT_RESULT
--------------------------
CREATE OR REPLACE VIEW HHS_WHRSC_HR.VW_R_CERT_RESULT
AS
SELECT DISTINCT
	REQUEST_NUMBER || TO_CHAR(DRVC.VACANCY_NUMBER) || DC.CERTIFICATE_NUMBER AS REQ_VAC_CERT,
	REQUEST_NUMBER AS REQUEST_NUMBER,
	TO_CHAR(DRVC.VACANCY_NUMBER) AS VACANCY_NUMBER,
	ANNOUNCEMENT_NUMBER,
	CERTIFICATE_TYPE,
	DC.CERTIFICATE_NUMBER AS CERTIFICATE_NUMBER,
	POSITION_TITLE,
	REGEXP_REPLACE(LISTAGG(CERT_FILTER_SERIES, ',') 
		WITHIN GROUP (ORDER BY DCL.CERTIFICATE_NUMBER),'([^,]*)(,\1)+($|,)','\1\3') AS SERIES,
	CERT_FILTER_GRADE AS GRADE,
	REPLACE(CERT_FILTER_LOCATIONS, '|', ';') AS DUTY_LOCATION,
	DATE_CERTIFICATE_ISSUED,
	DATE_CERTIFICATE_SENT_TO_SO,
	TO_CHAR(SELECTIONS_MADE) AS SELECTIONS_MADE,
	CASE
		WHEN DNHT.ARRIVAL_VERIFIED_COMPLT_DATE IS NOT NULL
		THEN 'Hire' 
		ELSE 'Not Filled'
	END AS ACTION_TAKEN,
	DATE_HIRING_DECISN_RECD_IN_HR,
	MIN(INITIAL_NOTIFICATION_SEND_DATE) AS INITIAL_NOTIFICATION_SEND_DATE,
	DATE_AUDIT_COMPLETED
FROM DSS_REQUEST_VACNCY_COMBINATION DRVC
	LEFT JOIN HHS_WHRSC_HR.DSS_CERTIFICATES DC
		ON DC.VACANCY_IDENTIFICATION_NUMBER= DRVC.VACANCY_NUMBER
	LEFT JOIN HHS_WHRSC_HR.DSS_CERTIFICATE_LOCATIONS DCL
		ON DC.CERTIFICATE_NUMBER = DCL.CERTIFICATE_NUMBER
	LEFT JOIN HHS_WHRSC_HR.DSS_APPLICANT_NOTIFICATIONS DAN
		ON DRVC.VACANCY_NUMBER = DAN.VACANCY_NUMBER
		AND DAN.APPLICATN_NOTIFICATN_TEMPLATE = 'Disposition'
	LEFT JOIN HHS_WHRSC_HR.DSS_NEW_HIRE_VACANCY_REQUEST DNHVR 
		ON DRVC.REQUEST_NUMBER = DNHVR.NH_REQUEST_NUMBER
	LEFT JOIN HHS_WHRSC_HR.DSS_NEW_HIRE_TASKS DNHT 
		ON DNHVR.NEW_HIRE_NUMBER = DNHT.NEW_HIRE_NUMBER
WHERE DC.CERTIFICATE_NUMBER IS NOT NULL
AND DRVC.REQUEST_NUMBER IS NOT NULL
GROUP BY
	REQUEST_NUMBER || TO_CHAR(DRVC.VACANCY_NUMBER),
	REQUEST_NUMBER,
	TO_CHAR(DRVC.VACANCY_NUMBER),
	ANNOUNCEMENT_NUMBER, 
	CERTIFICATE_TYPE,
	DC.CERTIFICATE_NUMBER,
	POSITION_TITLE,
	CERT_FILTER_GRADE,
	CERT_FILTER_LOCATIONS,
	DATE_CERTIFICATE_ISSUED,
	DATE_CERTIFICATE_SENT_TO_SO,
	SELECTIONS_MADE,
	ARRIVAL_VERIFIED_COMPLT_DATE,
	DATE_HIRING_DECISN_RECD_IN_HR,
	DATE_AUDIT_COMPLETED;

--------------------------
--VW_R_POS_RESULT
--------------------------
CREATE OR REPLACE VIEW HHS_WHRSC_HR.VW_R_POS_RESULT
AS
SELECT 
	DISTINCT 
	REQUEST_NUMBER,
	CLEARANCE_LEVEL_REQUIRED
FROM DSS_REQUESTS;


--------------------------
--VW_R_REQ_POS_RESULT
--------------------------
CREATE OR REPLACE VIEW HHS_WHRSC_HR.VW_R_REQ_POS_RESULT
AS
SELECT
	REQUEST_NUMBER,
	POSITION_DESCRIPTION_TITLE,
	DESCRIPTION,
	REGEXP_REPLACE(LISTAGG(DUTY_LOCATION, ';')
			WITHIN GROUP(ORDER BY DUTY_LOCATION),'([^;]*)(;\1)+($|;)','\1\3') AS DUTY_LOCATION
FROM
(
	SELECT 
		REQ.REQUEST_NUMBER,
		TO_CHAR(VACANCY_NUMBER) AS VACANCY_NUMBER,
		POSITION_DESCRIPTION_TITLE,
		TO_CHAR(DESCRIPTION) AS DESCRIPTION,
		CASE
			WHEN LOC.LOCATION_CITY IS NOT NULL
			THEN LOC.LOCATION_CITY || ', ' || LOC.LOCATION_STATE_ABBR || ' ' || LOC.LOCATION_COUNTRY
		END AS DUTY_LOCATION
	FROM HHS_WHRSC_HR.DSS_REQUEST_VACNCY_COMBINATION RVC
		LEFT JOIN HHS_WHRSC_HR.DSS_REQUEST_RATING_COMBINATION RRC
			ON RVC.REQUEST_NUMBER = RRC.REQUEST_NUMBER
		LEFT JOIN HHS_WHRSC_HR.DSS_REQUESTS REQ
			ON RVC.REQUEST_NUMBER = REQ.REQUEST_NUMBER
		LEFT JOIN HHS_WHRSC_HR.DSS_REQUEST_LOCATIONS LOC
			ON RVC.REQUEST_NUMBER = LOC.REQUEST_NUMBER
)
GROUP BY
	REQUEST_NUMBER,
	POSITION_DESCRIPTION_TITLE,
	DESCRIPTION;


--------------------------------
-- DDL FOR APPOINTMENT VIEWS           
--------------------------------
--------------------------------

---------------------
--VW_A_VAC_ANN_RESULT
---------------------
CREATE OR REPLACE VIEW HHS_WHRSC_HR.VW_A_VAC_ANN_RESULT
AS
SELECT
	NH_REQUEST_NUMBER || TO_CHAR(DNHVR.NH_VACANCY_NUMBER) AS REQ_VAC,
	NH_REQUEST_NUMBER AS REQUEST_NUMBER,
	TO_CHAR(DNHVR.NH_VACANCY_NUMBER) AS VACANCY_NUMBER,
	VACANCY_ANNOUNCEMENT_NUMBER ,
	SUPERVISORY_POSITION,
	CASE WHEN DNHF.ROWID IS NOT NULL
		THEN 'Yes'
		ELSE 'No'
	END AS OF_306_ASSGND_IN_ONBRDG_MNGR,
	REQUEST_TYPE AS RLTSHP_TO_RCRMT_ACTN,
	NH_POSITION_DESCRIPTION_NUMBER AS JOB_CODE,
	CLEARANCE_LEVEL_REQUIRED,
	CASE WHEN
		DNHVR.NH_VACANCY_NUMBER IS NOT NULL 
		THEN 'Competitive'
		ELSE 'Non-Competitive'
	END AS TYPE_OF_SELECTION,
	NVL(NH_ACTUAL_START_DATE, NH_PROJECTED_START_DATE) AS EOD
FROM HHS_WHRSC_HR.DSS_NEW_HIRE_VACANCY_REQUEST DNHVR
	LEFT JOIN HHS_WHRSC_HR.DSS_VACANCY DV
		ON DNHVR.NH_VACANCY_NUMBER = DV.VACANCY_IDENTIFICATION_NUMBER
	LEFT JOIN HHS_WHRSC_HR.DSS_REQUESTS DR
		ON DNHVR.NH_REQUEST_NUMBER = DR.REQUEST_NUMBER
	LEFT JOIN HHS_WHRSC_HR.DSS_NEW_HIRE_FORMS DNHF
		ON DNHVR.NEW_HIRE_NUMBER = DNHF.NEW_HIRE_NUMBER
		AND DNHF.NH_FORM_NUMBER = 'OF 306'
	LEFT JOIN HHS_WHRSC_HR.DSS_NEW_HIRES DNH
		ON DNHVR.NEW_HIRE_NUMBER = DNH.NEW_HIRE_NUMBER
WHERE NH_REQUEST_NUMBER IS NOT NULL;

---------------------
--VW_A_CERT_RESULT
---------------------
CREATE OR REPLACE VIEW HHS_WHRSC_HR.VW_A_CERT_RESULT
AS
SELECT
	DNHVR.NH_REQUEST_NUMBER || TO_CHAR(DNHVR.NH_VACANCY_NUMBER || DC.CERTIFICATE_NUMBER) AS REQ_VAC_CERT,
	DNHVR.NH_REQUEST_NUMBER AS REQUEST_NUMBER,
	TO_CHAR(DNHVR.NH_VACANCY_NUMBER) AS VACANCY_NUMBER,
	DC.CERTIFICATE_NUMBER AS CERTIFICATE_NUMBER,
	CERTIFICATE_TYPE,
	NH_POSITION_TITLE AS POSITION_TITLE,
	NH_PAY_PLAN AS PAY_PLAN,
	NH_SERIES AS SERIES,
	NH_GRADE AS GRADE,
	FULL_PERFORMANCE_LEVEL,
	DATE_CERTIFICATE_SENT_TO_SO,
	DATE_HIRING_DECISN_RECD_IN_HR,
	SEND_TENTATV_OFFER_COMPLT_DATE AS DATE_OF_TENTATV_OFFER,
	SEND_OFFICL_OFFER_COMPLT_DATE AS DATE_OF_OFFCL_OFFER,
	SEND_OFFICL_OFFER_COMPLT_DATE AS DATE_OFFCL_OFFER_SENT
FROM HHS_WHRSC_HR.DSS_NEW_HIRE_VACANCY_REQUEST DNHVR
	LEFT JOIN HHS_WHRSC_HR.DSS_NEW_HIRES DNH
		ON DNHVR.NEW_HIRE_NUMBER = DNH.NEW_HIRE_NUMBER
	LEFT JOIN HHS_WHRSC_HR.DSS_VACANCY DV
		ON DNHVR.NH_VACANCY_NUMBER = DV.VACANCY_IDENTIFICATION_NUMBER
	LEFT JOIN HHS_WHRSC_HR.DSS_CERTIFICATES DC
		ON DNHVR.CERTIFICATE_NUMBER = DC.CERTIFICATE_NUMBER
	LEFT JOIN HHS_WHRSC_HR.DSS_NEW_HIRE_TASKS DNHT
		ON DNHVR.NEW_HIRE_NUMBER = DNHT.NEW_HIRE_NUMBER
WHERE DNHVR.NH_REQUEST_NUMBER IS NOT NULL;
		
---------------------
--VW_A_DUTY_LOC_RESULT
---------------------
CREATE OR REPLACE VIEW HHS_WHRSC_HR.VW_A_DUTY_LOC_RESULT
AS
SELECT
	DNHVR.NH_REQUEST_NUMBER || TO_CHAR(DNHVR.NH_VACANCY_NUMBER) || DC.CERTIFICATE_NUMBER || NH_DUTY_LOCATION AS REQ_VAC_CERT_DL,
	DNHVR.NH_REQUEST_NUMBER AS REQUEST_NUMBER,
	TO_CHAR(DNHVR.NH_VACANCY_NUMBER) AS VACANCY_NUMBER,
	DC.CERTIFICATE_NUMBER AS CERTIFICATE_NUMBER,
	NH_DUTY_LOCATION AS DUTY_LOCATION,
	NH_DUTY_LOCATION_CODE AS DUTY_LOCATION_CODE
FROM HHS_WHRSC_HR.DSS_NEW_HIRE_VACANCY_REQUEST DNHVR
	LEFT JOIN HHS_WHRSC_HR.DSS_NEW_HIRES DNH
		ON DNHVR.NEW_HIRE_NUMBER = DNH.NEW_HIRE_NUMBER
	LEFT JOIN HHS_WHRSC_HR.DSS_VACANCY DV
		ON DNHVR.NH_VACANCY_NUMBER = DV.VACANCY_IDENTIFICATION_NUMBER
	LEFT JOIN HHS_WHRSC_HR.DSS_CERTIFICATES DC
		ON DNHVR.CERTIFICATE_NUMBER = DC.CERTIFICATE_NUMBER
	LEFT JOIN HHS_WHRSC_HR.DSS_NEW_HIRE_TASKS DNHT
		ON DNHVR.NEW_HIRE_NUMBER = DNHT.NEW_HIRE_NUMBER
WHERE DNHVR.NH_REQUEST_NUMBER IS NOT NULL;
